In [3]:
import pyspedas
from pytplot import tplot, tplot_names, options, get_data

In [4]:
import numpy as np

In [5]:
import pandas as pd

In [6]:
file_path = 'possibles_same_side.csv'

all_bursts = pd.read_csv(file_path)

print(all_bursts.head())

       Start time        End time  High frequency (Hz)  Low frequency (Hz)  \
0  2023-1-1/01:30  2023-1-1/04:00           10000000.0             50000.0
1  2023-1-3/06:25  2023-1-3/09:00           20000000.0             70000.0
2  2023-1-4/03:14  2023-1-4/03:20           10000000.0            600000.0
3  2023-1-4/05:53  2023-1-4/06:15           20000000.0            300000.0
4  2023-1-4/09:19  2023-1-4/09:24           20000000.0            600000.0

  GOES Flare Notes (corona loop brightening, etc.)
0    T     T                                  Loop
1    T     T                                  Loop
2    F   NaN                                   NaN
3    T     T                                  Loop
4    F   NaN                                   NaN

In [7]:
bursts = all_bursts[(all_bursts["GOES"] == "T") & (all_bursts["Flare"] == "T")]
bursts

,Start time,End time,High frequency (Hz),Low frequency (Hz),GOES,Flare,"Notes (corona loop brightening, etc.)"
0,2023-1-1/01:30,2023-1-1/04:00,10000000.0,50000.0,T,T,Loop
1,2023-1-3/06:25,2023-1-3/09:00,20000000.0,70000.0,T,T,Loop
3,2023-1-4/05:53,2023-1-4/06:15,20000000.0,300000.0,T,T,Loop
12,2023-1-6/08:29,2023-1-6/08:40,20000000.0,200000.0,T,T,Loop
13,2023-1-6/09:36,2023-1-6/09:48,10000000.0,300000.0,T,T,Loop & Spot
...,...,...,...,...,...,...,...
288,2023-8-6/18:26,2023-8-6/20:24,15000000.0,70000.0,T,T,Spot
289,2023-8-6/22:34,2023-8-6/23:42,20000000.0,30000.0,T,T,Spot
299,2023-8-7/20:39,2023-8-8/00:09,7000000.0,40000.0,T,T,Spot
300,2023-8-7/23:51,2023-8-8/00:16,20000000.0,600000.0,T,T,Spot
301,2023-8-8/09:25,2023-8-8/09:54,20000000.0,130000.0,T,T,Spot

In [8]:
freq_change = bursts["High frequency (Hz)"] - bursts["Low frequency (Hz)"]
bursts["Frequency Change"] = freq_change

bursts['Start time'] = pd.to_datetime(bursts['Start time'], format='%Y-%m-%d/%H:%M', errors='coerce')
bursts['End time'] = pd.to_datetime(bursts['End time'], format='%Y-%m-%d/%H:%M', errors='coerce')
bursts['Duration (seconds)'] = (bursts['End time'] - bursts['Start time']).dt.total_seconds()

drift_rate = bursts["Frequency Change"] / bursts["Duration (seconds)"]
bursts["Drift Rate (Hz/s)"] = drift_rate
bursts.head()

30-Oct-24 15:03:29: /var/folders/j7/8bwn58gn2hg5r0w_w0r9xm300000gn/T/ipykernel_70741/1277002261.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bursts["Frequency Change"] = freq_change

30-Oct-24 15:03:29: /var/folders/j7/8bwn58gn2hg5r0w_w0r9xm300000gn/T/ipykernel_70741/1277002261.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bursts['Start time'] = pd.to_datetime(bursts['Start time'], format='%Y-%m-%d/%H:%M', errors='coerce')

30-Oct-24 15:03:29: /var/folders/j7/8bwn58gn2hg5r0w_w0r9xm300000gn/T/ipykernel_70741/1277002261.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bursts['End time'] = pd.to_datetime(bursts['End time'], format='%Y-%m-%d/%H:%M', errors='coerce')

30-Oct-24 15:03:29: /var/folders/j7/8bwn58gn2hg5r0w_w0r9xm300000gn/T/ipykernel_70741/1277002261.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bursts['Duration (seconds)'] = (bursts['End time'] - bursts['Start time']).dt.total_seconds()

30-Oct-24 15:03:29: /var/folders/j7/8bwn58gn2hg5r0w_w0r9xm300000gn/T/ipykernel_70741/1277002261.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bursts["Drift Rate (Hz/s)"] = drift_rate

,Start time,End time,High frequency (Hz),Low frequency (Hz),GOES,Flare,"Notes (corona loop brightening, etc.)",Frequency Change,Duration (seconds),Drift Rate (Hz/s)
0,2023-01-01 01:30:00,2023-01-01 04:00:00,10000000.0,50000.0,T,T,Loop,9950000.0,9000.0,1105.555556
1,2023-01-03 06:25:00,2023-01-03 09:00:00,20000000.0,70000.0,T,T,Loop,19930000.0,9300.0,2143.010753
3,2023-01-04 05:53:00,2023-01-04 06:15:00,20000000.0,300000.0,T,T,Loop,19700000.0,1320.0,14924.242424
12,2023-01-06 08:29:00,2023-01-06 08:40:00,20000000.0,200000.0,T,T,Loop,19800000.0,660.0,30000.000000
13,2023-01-06 09:36:00,2023-01-06 09:48:00,10000000.0,300000.0,T,T,Loop & Spot,9700000.0,720.0,13472.222222

In [9]:
negative_row = bursts[bursts["Duration (seconds)"] < 0]
negative_row.head()

Empty DataFrame
Columns: [Start time, End time, High frequency (Hz), Low frequency (Hz), GOES, Flare, Notes (corona loop brightening, etc.), Frequency Change, Duration (seconds), Drift Rate (Hz/s)]
Index: []

In [10]:
with_flare = bursts

In [11]:
from pytplot import get_data
from matplotlib import pyplot as plt
%matplotlib tk
from matplotlib.colors import LogNorm

In [12]:
import matplotlib.pyplot as plt

freq_change = bursts["Drift Rate (Hz/s)"].dropna()

plt.hist(drift_rate, bins=10, edgecolor='black')

plt.title('Drift Rate Histogram')
plt.xlabel('Drift Rate (Hz/s)')
plt.ylabel('Count')

plt.show()

In [13]:
import matplotlib.pyplot as plt

freq_change = bursts["Duration (seconds)"].dropna()

plt.figure()
plt.hist(bursts['Duration (seconds)'], bins=10, edgecolor='black')

plt.title('Duration Histogram')
plt.xlabel('Duration (s)')
plt.ylabel('Count')

plt.show()

In [14]:
# log scale duration hist
duration = bursts["Duration (seconds)"].dropna()
log_bins = np.logspace(np.log10(duration.min()), np.log10(duration.max()), 10)

plt.figure()
plt.hist(duration, bins=log_bins, edgecolor='black')
plt.xscale('log')
plt.title('Duration Histogram')
plt.xlabel('Duration (s)')
plt.ylabel('Count')

plt.show()

In [15]:
# log scale drift rate hist
drift_rate = bursts["Drift Rate (Hz/s)"].dropna()
log_bins = np.logspace(np.log10(drift_rate.min()), np.log10(drift_rate.max()), 10)

plt.figure()
plt.hist(drift_rate, bins=log_bins, edgecolor='black')
plt.xscale('log')
plt.title('Drift Rate Histogram')
plt.xlabel('Drift (Hz/s)')
plt.ylabel('Count')

plt.show()

In [16]:
# wrong scale
freq_change = bursts["Duration (seconds)"].dropna()
log_bins = np.logspace(np.log10(duration.min()), np.log10(duration.max()), 10)

# change alpha
plt.hist(duration, bins=log_bins, edgecolor='black', alpha=0.5, label='Duration (s)')
plt.xscale('log')
plt.title('Duration Histogram')
plt.xlabel('Duration (s)')
plt.ylabel('Count')
plt.legend()

plt.show()

drift_rate = bursts["Drift Rate (Hz/s)"].dropna()

plt.hist(drift_rate, bins=log_bins, edgecolor='black', alpha=0.5, label='Drift (Hz/s)')
plt.xscale('log')
plt.title('Drift Rate Histogram')
plt.xlabel('Value (log scale)')
plt.ylabel('Count')
plt.legend()

plt.show()

In [17]:
import seaborn as sns

In [18]:
# original scale scattor plot for with flare
sns.scatterplot(data = bursts, x = bursts["Duration (seconds)"], y = bursts["Drift Rate (Hz/s)"])

plt.figure()
plt.title('Duration vs Drift Rate in Log 10')
plt.xlabel('Duration (seconds) (log 10)')
plt.ylabel('Drift Rate (Hz/s) (log 10)')

plt.show()

In [19]:
# log 10 scale scatter plot for with flare
sns.scatterplot(data = bursts, x = np.log10(bursts["Duration (seconds)"]), y = np.log10(bursts["Drift Rate (Hz/s)"]))

plt.title('Duration vs Drift Rate in Log 10')
plt.xlabel('Duration (seconds) (log 10)')
plt.ylabel('Drift Rate (Hz/s) (log 10)')

plt.show()

In [20]:
# filter without df
without_flare = all_bursts[(all_bursts["GOES"] == "T") & (all_bursts["Flare"] == "F")]
without_flare = without_flare.iloc[:, :-1]
without_flare

,Start time,End time,High frequency (Hz),Low frequency (Hz),GOES,Flare
7,2023-1-5/17:58,2023-1-5/18:50,20000000.0,600000.0,T,F
11,2023-1-6/07:53,2023-1-6/08:10,20000000.0,200000.0,T,F
76,2023-3-17/06:39,2023-3-17/07:10,20000000.0,1000000.0,T,F
90,2023-3-24/10:52,2023-3-24/12:09,6000000.0,90000.0,T,F
123,2023-4-18/15:21,2023-4-18/15:44,20000000.0,100000.0,T,F
129,2023-4-20/14:15,2023-4-20/14:27,14000000.0,200000.0,T,F
134,2023-4-22/07:50,2023-4-22/08:41,12000000.0,80000.0,T,F
136,2023-4-28/23:29,2023-4-28/23:31,20000000.0,200000.0,T,F
139,2023-4-30/13:03,2023-4-30/13:52,20000000.0,60000.0,T,F
140,2023-5-1/09:41,2023-5-1/10:07,4000000.0,100000.0,T,F
145,2023-5-4/21:34,2023-5-4/21:56,12000000.0,300000.0,T,F
147,2023-5-6/00:37,2023-5-6/01:45,20000000.0,80000.0,T,F
154,2023-5-16/13:35,2023-5-16/14:25,20000000.0,80000.0,T,F
156,2023-5-17/01:58,2023-5-17/02:36,9000000.0,300000.0,T,F
158,2023-5-18/07:08,2023-5-18/09:03,11000000.0,70000.0,T,F
171,2023-5-27/02:32,2023-5-27/02:40,10000000.0,400000.0,T,F
172,2023-5-28/16:45,2023-5-28/16:54,20000000.0,300000.0,T,F
174,2023-5-28/18:16,2023-5-28/18:32,13000000.0,400000.0,T,F
182,2023-6-13/15:08,2023-6-13/16:43,20000000.0,80000.0,T,F
184,2023-6-13/18:45,2023-6-13/20:18,12000000.0,80000.0,T,F
200,2023-6-27/20:40,2023-6-27/21:52,20000000.0,80000.0,T,F
213,2023-7-8/20:02,2023-7-8/21:04,20000000.0,100000.0,T,F
219,2023-7-11/11:15,2023-7-11/12:25,20000000.0,60000.0,T,F
230,2023-7-16/04:52,2023-7-16/05:48,20000000.0,30000.0,T,F
233,2023-7-16/23:54,2023-7-17/01:12,20000000.0,120000.0,T,F
253,2023-7-18/20:14,2023-7-18/21:35,20000000.0,60000.0,T,F
254,2023-7-19/04:11,2023-7-19/04:45,8000000.0,1800000.0,T,F
255,2023-7-19/09:44,2023-7-19/10:13,4000000.0,1800000.0,T,F
259,2023-7-20/06:20,2023-7-20/06:47,5000000.0,100000.0,T,F
261,2023-7-21/05:34,2023-7-21/05:53,13000000.0,200000.0,T,F
265,2023-7-22/13:32,2023-7-22/13:55,5000000.0,160000.0,T,F
267,2023-7-24/17:36,2023-7-24/20:20,5000000.0,40000.0,T,F
269,2023-7-26/17:06,2023-7-26/17:29,14000000.0,180000.0,T,F
290,2023-8-7/04:34,2023-8-7/05:35,15000000.0,1500000.0,T,F
291,2023-8-7/08:19,2023-8-7/08:32,20000000.0,80000.0,T,F
293,2023-8-7/12:05,2023-8-7/12:08,10000000.0,200000.0,T,F
295,2023-8-7/12:33,2023-8-7/13:05,14000000.0,70000.0,T,F
296,2023-8-7/13:30,2023-8-7/13:53,9000000.0,80000.0,T,F
298,2023-8-7/14:34,2023-8-7/15:27,20000000.0,30000.0,T,F
302,2023-8-8/16:44,2023-8-8/16:59,20000000.0,250000.0,T,F
303,2023-8-8/16:54,2023-8-8/17:53,20000000.0,150000.0,T,F

In [21]:
freq_change = without_flare["High frequency (Hz)"] - without_flare["Low frequency (Hz)"]
without_flare["Frequency Change"] = freq_change

without_flare['Start time'] = pd.to_datetime(without_flare['Start time'], format='%Y-%m-%d/%H:%M', errors='coerce')
without_flare['End time'] = pd.to_datetime(without_flare['End time'], format='%Y-%m-%d/%H:%M', errors='coerce')

without_flare['Duration (seconds)'] = (without_flare['End time'] - without_flare['Start time']).dt.total_seconds()

drift_rate = without_flare["Frequency Change"] / without_flare["Duration (seconds)"]
without_flare["Drift Rate (Hz/s)"] = drift_rate

without_flare

,Start time,End time,High frequency (Hz),Low frequency (Hz),GOES,Flare,Frequency Change,Duration (seconds),Drift Rate (Hz/s)
7,2023-01-05 17:58:00,2023-01-05 18:50:00,20000000.0,600000.0,T,F,19400000.0,3120.0,6217.948718
11,2023-01-06 07:53:00,2023-01-06 08:10:00,20000000.0,200000.0,T,F,19800000.0,1020.0,19411.764706
76,2023-03-17 06:39:00,2023-03-17 07:10:00,20000000.0,1000000.0,T,F,19000000.0,1860.0,10215.053763
90,2023-03-24 10:52:00,2023-03-24 12:09:00,6000000.0,90000.0,T,F,5910000.0,4620.0,1279.220779
123,2023-04-18 15:21:00,2023-04-18 15:44:00,20000000.0,100000.0,T,F,19900000.0,1380.0,14420.289855
129,2023-04-20 14:15:00,2023-04-20 14:27:00,14000000.0,200000.0,T,F,13800000.0,720.0,19166.666667
134,2023-04-22 07:50:00,2023-04-22 08:41:00,12000000.0,80000.0,T,F,11920000.0,3060.0,3895.424837
136,2023-04-28 23:29:00,2023-04-28 23:31:00,20000000.0,200000.0,T,F,19800000.0,120.0,165000.000000
139,2023-04-30 13:03:00,2023-04-30 13:52:00,20000000.0,60000.0,T,F,19940000.0,2940.0,6782.312925
140,2023-05-01 09:41:00,2023-05-01 10:07:00,4000000.0,100000.0,T,F,3900000.0,1560.0,2500.000000
145,2023-05-04 21:34:00,2023-05-04 21:56:00,12000000.0,300000.0,T,F,11700000.0,1320.0,8863.636364
147,2023-05-06 00:37:00,2023-05-06 01:45:00,20000000.0,80000.0,T,F,19920000.0,4080.0,4882.352941
154,2023-05-16 13:35:00,2023-05-16 14:25:00,20000000.0,80000.0,T,F,19920000.0,3000.0,6640.000000
156,2023-05-17 01:58:00,2023-05-17 02:36:00,9000000.0,300000.0,T,F,8700000.0,2280.0,3815.789474
158,2023-05-18 07:08:00,2023-05-18 09:03:00,11000000.0,70000.0,T,F,10930000.0,6900.0,1584.057971
171,2023-05-27 02:32:00,2023-05-27 02:40:00,10000000.0,400000.0,T,F,9600000.0,480.0,20000.000000
172,2023-05-28 16:45:00,2023-05-28 16:54:00,20000000.0,300000.0,T,F,19700000.0,540.0,36481.481481
174,2023-05-28 18:16:00,2023-05-28 18:32:00,13000000.0,400000.0,T,F,12600000.0,960.0,13125.000000
182,2023-06-13 15:08:00,2023-06-13 16:43:00,20000000.0,80000.0,T,F,19920000.0,5700.0,3494.736842
184,2023-06-13 18:45:00,2023-06-13 20:18:00,12000000.0,80000.0,T,F,11920000.0,5580.0,2136.200717
200,2023-06-27 20:40:00,2023-06-27 21:52:00,20000000.0,80000.0,T,F,19920000.0,4320.0,4611.111111
213,2023-07-08 20:02:00,2023-07-08 21:04:00,20000000.0,100000.0,T,F,19900000.0,3720.0,5349.462366
219,2023-07-11 11:15:00,2023-07-11 12:25:00,20000000.0,60000.0,T,F,19940000.0,4200.0,4747.619048
230,2023-07-16 04:52:00,2023-07-16 05:48:00,20000000.0,30000.0,T,F,19970000.0,3360.0,5943.452381
233,2023-07-16 23:54:00,2023-07-17 01:12:00,20000000.0,120000.0,T,F,19880000.0,4680.0,4247.863248
253,2023-07-18 20:14:00,2023-07-18 21:35:00,20000000.0,60000.0,T,F,19940000.0,4860.0,4102.880658
254,2023-07-19 04:11:00,2023-07-19 04:45:00,8000000.0,1800000.0,T,F,6200000.0,2040.0,3039.215686
255,2023-07-19 09:44:00,2023-07-19 10:13:00,4000000.0,1800000.0,T,F,2200000.0,1740.0,1264.367816
259,2023-07-20 06:20:00,2023-07-20 06:47:00,5000000.0,100000.0,T,F,4900000.0,1620.0,3024.691358
261,2023-07-21 05:34:00,2023-07-21 05:53:00,13000000.0,200000.0,T,F,12800000.0,1140.0,11228.070175
265,2023-07-22 13:32:00,2023-07-22 13:55:00,5000000.0,160000.0,T,F,4840000.0,1380.0,3507.246377
267,2023-07-24 17:36:00,2023-07-24 20:20:00,5000000.0,40000.0,T,F,4960000.0,9840.0,504.065041
269,2023-07-26 17:06:00,2023-07-26 17:29:00,14000000.0,180000.0,T,F,13820000.0,1380.0,10014.492754
290,2023-08-07 04:34:00,2023-08-07 05:35:00,15000000.0,1500000.0,T,F,13500000.0,3660.0,3688.524590
291,2023-08-07 08:19:00,2023-08-07 08:32:00,20000000.0,80000.0,T,F,19920000.0,780.0,25538.461538
293,2023-08-07 12:05:00,2023-08-07 12:08:00,10000000.0,200000.0,T,F,9800000.0,180.0,54444.444444
295,2023-08-07 12:33:00,2023-08-07 13:05:00,14000000.0,70000.0,T,F,13930000.0,1920.0,7255.208333
296,2023-08-07 13:30:00,2023-08-07 13:53:00,9000000.0,80000.0,T,F,8920000.0,1380.0,6463.768116
298,2023-08-07 14:34:00,2023-08-07 15:27:00,20000000.0,30000.0,T,F,19970000.0,3180.0,6279.874214
302,2023-08-08 16:44:00,2023-08-08 16:59:00,20000000.0,250000.0,T,F,19750000.0,900.0,21944.444444
303,2023-08-08 16:54:00,2023-08-08 17:53:00,20000000.0,150000.0,T,F,19850000.0,3540.0,5607.344633

In [22]:
# find whether any NaN
nan_df = without_flare.isna()
print(nan_df)

     Start time  End time  High frequency (Hz)  Low frequency (Hz)   GOES  \
7         False     False                False               False  False
11        False     False                False               False  False
76        False     False                False               False  False
90        False     False                False               False  False
123       False     False                False               False  False
129       False     False                False               False  False
134       False     False                False               False  False
136       False     False                False               False  False
139       False     False                False               False  False
140       False     False                False               False  False
145       False     False                False               False  False
147       False     False                False               False  False
154       False     False                False               False  False
156       False     False                False               False  False
158       False     False                False               False  False
171       False     False                False               False  False
172       False     False                False               False  False
174       False     False                False               False  False
182       False     False                False               False  False
184       False     False                False               False  False
200       False     False                False               False  False
213       False     False                False               False  False
219       False     False                False               False  False
230       False     False                False               False  False
233       False     False                False               False  False
253       False     False                False               False  False
254       False     False                False               False  False
255       False     False                False               False  False
259       False     False                False               False  False
261       False     False                False               False  False
265       False     False                False               False  False
267       False     False                False               False  False
269       False     False                False               False  False
290       False     False                False               False  False
291       False     False                False               False  False
293       False     False                False               False  False
295       False     False                False               False  False
296       False     False                False               False  False
298       False     False                False               False  False
302       False     False                False               False  False
303       False     False                False               False  False

     Flare  Frequency Change  Duration (seconds)  Drift Rate (Hz/s)
7    False             False               False              False
11   False             False               False              False
76   False             False               False              False
90   False             False               False              False
123  False             False               False              False
129  False             False               False              False
134  False             False               False              False
136  False             False               False              False
139  False             False               False              False
140  False             False               False              False
145  False             False               False              False
147  False             False               False              False
154  False             False               False              False
156  False             False               False              False
158  False             False               False              False
171  False             False               False              False
172  False             False               False              False
174  False             False               False              False
182  False             False               False              False
184  False             False               False              False
200  False             False               False              False
213  False             False               False              False
219  False             False               False              False
230  False             False               False              False
233  False             False               False              False
253  False             False               False              False
254  False             False               False              False
255  False             False               False              False
259  False             False               False              False
261  False             False               False              False
265  False             False               False              False
267  False             False               False              False
269  False             False               False              False
290  False             False               False              False
291  False             False               False              False
293  False             False               False              False
295  False             False               False              False
296  False             False               False              False
298  False             False               False              False
302  False             False               False              False
303  False             False               False              False

In [23]:
# wrong scale
freq_change = without_flare["Duration (seconds)"].dropna()
log_bins = np.logspace(np.log10(duration.min()), np.log10(duration.max()), 10)

# change alpha
plt.hist(duration, bins=log_bins, edgecolor='black', alpha=0.5, label='Duration (s)')
plt.xscale('log')
plt.title('Duration Histogram')
plt.xlabel('Duration (s)')
plt.ylabel('Count')
plt.legend()

plt.show()

drift_rate = without_flare["Drift Rate (Hz/s)"].dropna()

plt.hist(drift_rate, bins=log_bins, edgecolor='black', alpha=0.5, label='Drift (Hz/s)')
plt.xscale('log')
plt.title('Drift Rate Histogram')
plt.xlabel('Drift (Hz/s)')
plt.ylabel('Count')
plt.legend()

plt.show()

In [24]:
# drift rate log histplot for without
drift_rate = without_flare["Drift Rate (Hz/s)"].dropna()
log_bins = np.logspace(np.log10(drift_rate.min()), np.log10(drift_rate.max()), 10)

plt.hist(drift_rate, bins=log_bins, edgecolor='black')
plt.xscale('log')
plt.title('Drift Rate Histogram')
plt.xlabel('Drift (Hz/s)')
plt.ylabel('Count')

plt.show()

In [25]:
# duration log histplot for without
duration = without_flare["Duration (seconds)"].dropna()
log_bins = np.logspace(np.log10(duration.min()), np.log10(duration.max()), 10)

plt.hist(duration, bins=log_bins, edgecolor='black')
plt.xscale('log')
plt.title('Duration Histogram')
plt.xlabel('Drift (Hz/s)')
plt.ylabel('Count')

plt.show()

In [26]:
# Check for missing values in each column
print(without_flare["Duration (seconds)"].isnull().sum())
print(without_flare["Drift Rate (Hz/s)"].isnull().sum())

0
0

In [27]:
# wrong scale
without_flare_cleaned = without_flare.dropna(subset=["Duration (seconds)", "Drift Rate (Hz/s)"])

freq_change = without_flare_cleaned["Duration (seconds)"]
drift_rate = without_flare_cleaned["Drift Rate (Hz/s)"]

plt.hist(freq_change, bins=log_bins, edgecolor='black', alpha=0.5, label='Duration (s)')
plt.hist(drift_rate, bins=log_bins, edgecolor='black', alpha=0.5, label='Drift (Hz/s)')
plt.xscale('log')
plt.title('Duration and Drift Rate Histogram')
plt.xlabel('Value (log scale)')
plt.ylabel('Count')
plt.legend()
plt.show()

In [28]:
# right scale: compare durtion with flare vs. without flare
duration_with = bursts["Duration (seconds)"]
duration_without = without_flare["Duration (seconds)"]

plt.hist(duration_with, bins=log_bins, edgecolor='black', alpha=0.5, label='Duration (s)')
plt.hist(duration_without, bins=log_bins, edgecolor='black', alpha=0.5, label='Drift (Hz/s)')
plt.xscale('log')
plt.title('Duration and Drift Rate Histogram')
plt.xlabel('Value (log scale)')
plt.ylabel('Count')
plt.legend()
plt.show()

In [29]:
# right scale: compare drift rate with flare vs. without flare
duration_with = bursts["Drift Rate (Hz/s)"]
duration_without = without_flare["Drift Rate (Hz/s)"]

plt.hist(duration_with, bins=log_bins, edgecolor='black', alpha=0.5, label='Duration (s)')
plt.hist(duration_without, bins=log_bins, edgecolor='black', alpha=0.5, label='Drift (Hz/s)')
plt.xscale('log')
plt.title('Duration and Drift Rate Histogram')
plt.xlabel('Value (log scale)')
plt.ylabel('Count')
plt.legend()
plt.show()

In [30]:
# original scale scattor plot for without flare
sns.scatterplot(data = without_flare, x = "Duration (seconds)", y = "Drift Rate (Hz/s)")

plt.title('Duration vs Drift Rate in Log 10')
plt.xlabel('Duration (seconds) (log 10)')
plt.ylabel('Drift Rate (Hz/s) (log 10)')

plt.show()

In [31]:
# log 10 scale scatter plot for with flare
sns.scatterplot(data = without_flare, x = np.log10(without_flare["Duration (seconds)"]), y = np.log10(without_flare["Drift Rate (Hz/s)"]))

plt.title('Duration vs Drift Rate in Log 10')
plt.xlabel('Duration (seconds) (log 10)')
plt.ylabel('Drift Rate (Hz/s) (log 10)')

plt.show()

In [32]:
# plot scatter plot side by side
# figsize changes the width of the 2 graphs (now is 15)
fig, ax = plt.subplots(1, 2, figsize=(15, 5))
sns.scatterplot(data = bursts, x = np.log10(bursts["Duration (seconds)"]), y = np.log10(bursts["Drift Rate (Hz/s)"]), ax = ax[0])


ax[0].set_title('Duration vs Drift Rate in Log 10')
ax[0].set_xlabel('log Duration (seconds)')
ax[0].set_ylabel('log Drift Rate (Hz/s)')

sns.scatterplot(data = without_flare, x = np.log10(without_flare["Duration (seconds)"]), y = np.log10(without_flare["Drift Rate (Hz/s)"]), ax = ax[1])

plt.title('Duration vs Drift Rate in Log 10')
plt.xlabel('log Duration (seconds)')
plt.ylabel('log Drift Rate (Hz/s)')

fig.show()

In [33]:
spot_bursts = bursts[bursts["Notes (corona loop brightening, etc.)"] == "Spot"]
spot_bursts

,Start time,End time,High frequency (Hz),Low frequency (Hz),GOES,Flare,"Notes (corona loop brightening, etc.)",Frequency Change,Duration (seconds),Drift Rate (Hz/s)
14,2023-01-06 10:20:00,2023-01-06 10:40:00,10000000.0,200000.0,T,T,Spot,9800000.0,1200.0,8166.666667
15,2023-01-06 12:07:00,2023-01-06 12:17:00,20000000.0,200000.0,T,T,Spot,19800000.0,600.0,33000.000000
18,2023-01-09 08:50:00,2023-01-09 09:05:00,30000000.0,100000.0,T,T,Spot,29900000.0,900.0,33222.222222
21,2023-01-09 18:48:00,2023-01-09 20:30:00,4000000.0,60000.0,T,T,Spot,3940000.0,6120.0,643.790850
23,2023-01-09 22:29:00,2023-01-10 00:00:00,6000000.0,60000.0,T,T,Spot,5940000.0,5460.0,1087.912088
...,...,...,...,...,...,...,...,...,...,...
288,2023-08-06 18:26:00,2023-08-06 20:24:00,15000000.0,70000.0,T,T,Spot,14930000.0,7080.0,2108.757062
289,2023-08-06 22:34:00,2023-08-06 23:42:00,20000000.0,30000.0,T,T,Spot,19970000.0,4080.0,4894.607843
299,2023-08-07 20:39:00,2023-08-08 00:09:00,7000000.0,40000.0,T,T,Spot,6960000.0,12600.0,552.380952
300,2023-08-07 23:51:00,2023-08-08 00:16:00,20000000.0,600000.0,T,T,Spot,19400000.0,1500.0,12933.333333
301,2023-08-08 09:25:00,2023-08-08 09:54:00,20000000.0,130000.0,T,T,Spot,19870000.0,1740.0,11419.540230

In [34]:
spot_duration = spot_bursts["Duration (seconds)"].dropna()
log_bins = np.logspace(np.log10(spot_duration.min()), np.log10(spot_duration.max()), 10)

plt.hist(spot_duration, bins=log_bins, edgecolor='black')
plt.xscale('log')
plt.title('Duration Histogram')
plt.xlabel('Drift (Hz/s)')
plt.ylabel('Count')

plt.show()

In [35]:
loop_bursts = bursts[bursts["Notes (corona loop brightening, etc.)"] == "Loop"]
loop_bursts.head()

,Start time,End time,High frequency (Hz),Low frequency (Hz),GOES,Flare,"Notes (corona loop brightening, etc.)",Frequency Change,Duration (seconds),Drift Rate (Hz/s)
0,2023-01-01 01:30:00,2023-01-01 04:00:00,10000000.0,50000.0,T,T,Loop,9950000.0,9000.0,1105.555556
1,2023-01-03 06:25:00,2023-01-03 09:00:00,20000000.0,70000.0,T,T,Loop,19930000.0,9300.0,2143.010753
3,2023-01-04 05:53:00,2023-01-04 06:15:00,20000000.0,300000.0,T,T,Loop,19700000.0,1320.0,14924.242424
12,2023-01-06 08:29:00,2023-01-06 08:40:00,20000000.0,200000.0,T,T,Loop,19800000.0,660.0,30000.000000
22,2023-01-09 20:52:00,2023-01-09 22:00:00,1000000.0,100000.0,T,T,Loop,900000.0,4080.0,220.588235

In [36]:
loop_duration = loop_bursts["Duration (seconds)"].dropna()
log_bins = np.logspace(np.log10(loop_duration.min()), np.log10(loop_duration.max()), 10)

plt.hist(loop_duration, bins=log_bins, edgecolor='black')
plt.xscale('log')
plt.title('Duration Histogram')
plt.xlabel('Drift (Hz/s)')
plt.ylabel('Count')

plt.show()

In [37]:
# scatter plot side by side for spot vs loop
fig, ax = plt.subplots(1, 2, figsize=(15, 5))
sns.scatterplot(data = spot_bursts, x = np.log10(spot_bursts["Duration (seconds)"]), y = np.log10(spot_bursts["Drift Rate (Hz/s)"]), ax = ax[0])
sns.scatterplot(data = loop_bursts, x = np.log10(loop_bursts["Duration (seconds)"]), y = np.log10(loop_bursts["Drift Rate (Hz/s)"]), ax = ax[1])
fig.show()

In [38]:
bursts = bursts.rename(columns={"Notes (corona loop brightening, etc.)": "Brightening"})
bursts.head(10)

,Start time,End time,High frequency (Hz),Low frequency (Hz),GOES,Flare,Brightening,Frequency Change,Duration (seconds),Drift Rate (Hz/s)
0,2023-01-01 01:30:00,2023-01-01 04:00:00,10000000.0,50000.0,T,T,Loop,9950000.0,9000.0,1105.555556
1,2023-01-03 06:25:00,2023-01-03 09:00:00,20000000.0,70000.0,T,T,Loop,19930000.0,9300.0,2143.010753
3,2023-01-04 05:53:00,2023-01-04 06:15:00,20000000.0,300000.0,T,T,Loop,19700000.0,1320.0,14924.242424
12,2023-01-06 08:29:00,2023-01-06 08:40:00,20000000.0,200000.0,T,T,Loop,19800000.0,660.0,30000.000000
13,2023-01-06 09:36:00,2023-01-06 09:48:00,10000000.0,300000.0,T,T,Loop & Spot,9700000.0,720.0,13472.222222
14,2023-01-06 10:20:00,2023-01-06 10:40:00,10000000.0,200000.0,T,T,Spot,9800000.0,1200.0,8166.666667
15,2023-01-06 12:07:00,2023-01-06 12:17:00,20000000.0,200000.0,T,T,Spot,19800000.0,600.0,33000.000000
16,2023-01-06 21:48:00,2023-01-06 22:30:00,20000000.0,100000.0,T,T,Loop & Spot,19900000.0,2520.0,7896.825397
18,2023-01-09 08:50:00,2023-01-09 09:05:00,30000000.0,100000.0,T,T,Spot,29900000.0,900.0,33222.222222
21,2023-01-09 18:48:00,2023-01-09 20:30:00,4000000.0,60000.0,T,T,Spot,3940000.0,6120.0,643.790850

In [39]:
# scatter plot, different notes have different colors
sns.scatterplot(data = bursts, 
                x = np.log10(bursts["Duration (seconds)"]), 
                y = np.log10(bursts["Drift Rate (Hz/s)"]), 
                hue = bursts["Brightening"])

In [40]:
# scatter plot, different notes have different colors
sns.histplot(data = bursts, 
                x = np.log10(bursts["Duration (seconds)"]),
                hue = bursts["Brightening"])

In [41]:
# scatter plot, different notes have different colors
sns.histplot(data = bursts, 
                x = np.log10(bursts["Drift Rate (Hz/s)"]),
                hue = bursts["Brightening"])

In [42]:
# histogram with Brightening types as hues, drift rate & duration side by side
fig, ax = plt.subplots(1, 2, figsize=(15, 5))
sns.histplot(data = bursts, 
                x = np.log10(bursts["Duration (seconds)"]),
                hue = bursts["Brightening"],
                ax = ax[0])
sns.histplot(data = bursts, 
                x = np.log10(bursts["Drift Rate (Hz/s)"]),
                hue = bursts["Brightening"],
                ax = ax[1])

ax[0].set_title('Duration Histogram in Log 10')
ax[0].set_xlabel('Duration (seconds) in power of 10')
ax[1].set_title('Drift Rate Histogram in Log 10')
ax[1].set_xlabel('Drift Rate (Hz/s) in power of 10')
fig.show()

In [43]:
# kde with Brightening types as hues, drift rate & duration side by side
fig, ax = plt.subplots(1, 2, figsize=(15, 5))
sns.kdeplot(data = bursts, 
                x = np.log10(bursts["Duration (seconds)"]),
                hue = bursts["Brightening"],
                bw_adjust = 0.5,
                ax = ax[0])
sns.kdeplot(data = bursts, 
                x = np.log10(bursts["Drift Rate (Hz/s)"]),
                hue = bursts["Brightening"],
                bw_adjust = 0.5,
                ax = ax[1])

ax[0].set_title('Duration Histogram in Log 10')
ax[0].set_xlabel('Duration (seconds) in power of 10')
ax[1].set_title('Drift Rate Histogram in Log 10')
ax[1].set_xlabel('Drift Rate (Hz/s) in power of 10')
fig.show()

In [44]:
bursts_cleaned = bursts[bursts["Brightening"].notna()]

duration_data = bursts_cleaned["Duration (seconds)"]
drift_rate_data = bursts_cleaned["Drift Rate (Hz/s)"]
brightening_data = bursts_cleaned["Brightening"].unique()

log_bins_duration = np.logspace(np.log10(duration_data.min()), np.log10(duration_data.max()), 20)
log_bins_drift_rate = np.logspace(np.log10(drift_rate_data.min()), np.log10(drift_rate_data.max()), 20)

colors = ['blue', 'orange', 'green']

fig, ax = plt.subplots(1, 2, figsize=(15, 5))

for i, brightening_type in enumerate(brightening_data):
    subset_duration = duration_data[bursts_cleaned["Brightening"] == brightening_type]
    hist_duration, bin_edges_duration = np.histogram(subset_duration, bins=log_bins_duration)
    
    ax[0].bar(bin_edges_duration[:-1], hist_duration, width=np.diff(bin_edges_duration), 
              alpha=0.5, color=colors[i], label=brightening_type, edgecolor="black")

ax[0].set_xscale('log')
ax[0].set_title('Log-Binned Histogram for Duration (seconds)')
ax[0].set_xlabel('Duration (seconds) (log scale)')
ax[0].set_ylabel('Frequency')
ax[0].legend(title='Brightening')

for i, brightening_type in enumerate(brightening_data):
    subset_drift_rate = drift_rate_data[bursts_cleaned["Brightening"] == brightening_type]
    hist_drift_rate, bin_edges_drift_rate = np.histogram(subset_drift_rate, bins=log_bins_drift_rate)
    
    ax[1].bar(bin_edges_drift_rate[:-1], hist_drift_rate, width=np.diff(bin_edges_drift_rate), 
              alpha=0.5, color=colors[i], label=brightening_type, edgecolor="black")

ax[1].set_xscale('log')
ax[1].set_title('Log-Binned Histogram for Drift Rate (Hz/s)')
ax[1].set_xlabel('Drift Rate (Hz/s) (log scale)')
ax[1].set_ylabel('Frequency')
ax[1].legend(title='Brightening')

plt.tight_layout()
plt.show()

In [45]:
# Calculate the standard error for each of the last three columns
standard_errors = bursts[['Frequency Change', 'Duration (seconds)', 'Drift Rate (Hz/s)']].std() / np.sqrt(len(bursts))

print(standard_errors)
print("\n")

# Standardize by the mean (to express as a percentage of the mean)
means = bursts[['Frequency Change', 'Duration (seconds)', 'Drift Rate (Hz/s)']].mean()
standard_errors_in_standard_units = standard_errors / means

# Standardize by the standard deviation (to express as z-scores)
std_devs = bursts[['Frequency Change', 'Duration (seconds)', 'Drift Rate (Hz/s)']].std()
standard_errors_z_scores = standard_errors / std_devs

print("Standard Error in Standard Units (Percentage of Mean):\n", standard_errors_in_standard_units)
print("\nStandard Error in Standard Units (Z-scores):\n", standard_errors_z_scores)

Frequency Change      533760.605973
Duration (seconds)       204.270871
Drift Rate (Hz/s)       1454.099906
dtype: float64


Standard Error in Standard Units (Percentage of Mean):
 Frequency Change      0.035219
Duration (seconds)    0.074184
Drift Rate (Hz/s)     0.115809
dtype: float64

Standard Error in Standard Units (Z-scores):
 Frequency Change      0.084515
Duration (seconds)    0.084515
Drift Rate (Hz/s)     0.084515
dtype: float64

In [46]:
# standard error for with flare
standard_errors = with_flare[['Frequency Change', 'Duration (seconds)', 'Drift Rate (Hz/s)']].std() / np.sqrt(len(bursts))

print("With flare: \n")
print('Duration: ', np.mean(with_flare['Duration (seconds)']), ' +/- ', np.std(with_flare['Duration (seconds)']))
print('Frequency Change: ', np.mean(with_flare['Frequency Change']), ' +/- ', np.std(with_flare['Frequency Change']))
print('Drift Rate: ', np.mean(with_flare['Drift Rate (Hz/s)']), ' +/- ', np.std(with_flare['Drift Rate (Hz/s)']))
print("\n")

# standard error for without flare
standard_errors = without_flare[['Frequency Change', 'Duration (seconds)', 'Drift Rate (Hz/s)']].std() / np.sqrt(len(bursts))

print("Without flare: \n")
print('Duration: ', np.mean(without_flare['Duration (seconds)']), ' +/- ', np.std(without_flare['Duration (seconds)']))
print('Frequency Change: ', np.mean(without_flare['Frequency Change']), ' +/- ', np.std(without_flare['Frequency Change']))
print('Drift Rate: ', np.mean(without_flare['Drift Rate (Hz/s)']), ' +/- ', np.std(without_flare['Drift Rate (Hz/s)']))
print("\n")

# standard error for with spot
standard_errors = spot_bursts[['Frequency Change', 'Duration (seconds)', 'Drift Rate (Hz/s)']].std() / np.sqrt(len(bursts))

print("With spot: \n")
print('Duration: ', np.mean(spot_bursts['Duration (seconds)']), ' +/- ', np.std(spot_bursts['Duration (seconds)']))
print('Frequency Change: ', np.mean(spot_bursts['Frequency Change']), ' +/- ', np.std(spot_bursts['Frequency Change']))
print('Drift Rate: ', np.mean(spot_bursts['Drift Rate (Hz/s)']), ' +/- ', np.std(spot_bursts['Drift Rate (Hz/s)']))
print("\n")

# standard error for with loop
standard_errors = loop_bursts[['Frequency Change', 'Duration (seconds)', 'Drift Rate (Hz/s)']].std() / np.sqrt(len(bursts))

print("With loop: \n")
print('Duration: ', np.mean(loop_bursts['Duration (seconds)']), ' +/- ', np.std(loop_bursts['Duration (seconds)']))
print('Frequency Change: ', np.mean(loop_bursts['Frequency Change']), ' +/- ', np.std(loop_bursts['Frequency Change']))
print('Drift Rate: ', np.mean(loop_bursts['Drift Rate (Hz/s)']), ' +/- ', np.std(loop_bursts['Drift Rate (Hz/s)']))
print("\n")

print(len(with_flare) / (len(with_flare) + len(without_flare)) * 100)
print(len(without_flare) / (len(with_flare) + len(without_flare)) * 100)
print(len(with_flare) + len(without_flare))
print(np.sqrt(len(with_flare) + len(without_flare)))
print(100/np.sqrt(len(with_flare) + len(without_flare)))

With flare:

Duration:  2753.5714285714284  +/-  2408.318047170375
Frequency Change:  15155357.142857144  +/-  6292944.735485727
Drift Rate:  12555.982383191269  +/-  17143.585053611052


Without flare:

Duration:  2708.7804878048782  +/-  2004.069268947864
Frequency Change:  14468048.780487806  +/-  5849241.860197258
Drift Rate:  13237.037716386101  +/-  26117.51148665343


With spot:

Duration:  2956.0  +/-  2512.41397862693
Frequency Change:  15306666.666666666  +/-  6230242.549228902
Drift Rate:  11613.155617290584  +/-  16781.619799838245


With loop:

Duration:  2331.0  +/-  2054.9693428370165
Frequency Change:  15272250.0  +/-  6134924.811071444
Drift Rate:  13647.873921690096  +/-  15949.17667637641


77.34806629834254
22.65193370165746
181
13.45362404707371
7.432941462471663

In [47]:
# Poisson noise

# Calculate the mean for each of the last three columns
means = bursts[['Frequency Change', 'Duration (seconds)', 'Drift Rate (Hz/s)']].mean()

# Calculate the Poisson noise for each column (square root of the mean)
poisson_noise = np.sqrt(means)

print("Mean values of each column:\n", means)
print("\nPoisson Noise for each column:\n", poisson_noise)

Mean values of each column:
 Frequency Change      1.515536e+07
Duration (seconds)    2.753571e+03
Drift Rate (Hz/s)     1.255598e+04
dtype: float64

Poisson Noise for each column:
 Frequency Change      3892.988202
Duration (seconds)      52.474484
Drift Rate (Hz/s)      112.053480
dtype: float64

In [48]:
# poisson noise for with flare
means = with_flare[['Frequency Change', 'Duration (seconds)', 'Drift Rate (Hz/s)']].mean()
poisson_noise = np.sqrt(means)

print("\nPoisson Noise for with flare:\n", poisson_noise)

# poisson noise for without flare
means = without_flare[['Frequency Change', 'Duration (seconds)', 'Drift Rate (Hz/s)']].mean()
poisson_noise = np.sqrt(means)

print("\nPoisson Noise for without flare:\n", poisson_noise)

# poisson noise for with spot
means = spot_bursts[['Frequency Change', 'Duration (seconds)', 'Drift Rate (Hz/s)']].mean()
poisson_noise = np.sqrt(means)

print("\nPoisson Noise for with spot:\n", poisson_noise)

# poisson noise for with loop
means = loop_bursts[['Frequency Change', 'Duration (seconds)', 'Drift Rate (Hz/s)']].mean()
poisson_noise = np.sqrt(means)

print("\nPoisson Noise for with loop:\n", poisson_noise)

Poisson Noise for with flare:
 Frequency Change      3892.988202
Duration (seconds)      52.474484
Drift Rate (Hz/s)      112.053480
dtype: float64

Poisson Noise for without flare:
 Frequency Change      3803.688839
Duration (seconds)      52.045946
Drift Rate (Hz/s)      115.052326
dtype: float64

Poisson Noise for with spot:
 Frequency Change      3912.373534
Duration (seconds)      54.369109
Drift Rate (Hz/s)      107.764352
dtype: float64

Poisson Noise for with loop:
 Frequency Change      3907.972620
Duration (seconds)      48.280431
Drift Rate (Hz/s)      116.824115
dtype: float64

In [99]:
import matplotlib.pyplot as plt

duration = with_flare["Duration (seconds)"].dropna()
log_bins = np.logspace(np.log10(duration.min()), np.log10(duration.max()), 10)

plt.figure()
H, bins, patche = plt.hist(duration, bins=log_bins, edgecolor='black')
plt.xscale('log')
plt.title('Duration Histogram')
plt.xlabel('Duration (s)')
plt.ylabel('Count')

counts, bins = np.histogram(duration, bins=log_bins)
plt.plot((bins[:-1] + bins[1:]) / 2, counts)

plt.errorbar(bins[:-1], counts, yerr=np.sqrt(len(with_flare)))

plt.show()