In [1]:
import pandas as pd

# Read the CSV file
possibles = pd.read_csv('possibles.csv')

# Display the first few rows
print(possibles.head())

       Start time        End time  High frequency (Hz)  Low frequency (Hz)
0  2023-1-1/01:30  2023-1-1/04:00           10000000.0             50000.0
1  2023-1-3/06:25  2023-1-3/09:00           20000000.0             70000.0
2  2023-1-4/03:14  2023-1-4/03:20           10000000.0            600000.0
3  2023-1-4/05:53  2023-1-4/06:15           20000000.0            300000.0
4  2023-1-4/03:14  2023-1-4/03:29           10000000.0            600000.0

In [3]:
!pip install datascience

Requirement already satisfied: datascience in /opt/anaconda3/lib/python3.12/site-packages (0.17.6)
Requirement already satisfied: folium>=0.9.1 in /opt/anaconda3/lib/python3.12/site-packages (from datascience) (0.17.0)
Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.12/site-packages (from datascience) (69.5.1)
Requirement already satisfied: matplotlib>=3.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from datascience) (3.8.4)
Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.12/site-packages (from datascience) (2.2.2)
Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.12/site-packages (from datascience) (1.13.1)
Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.12/site-packages (from datascience) (1.26.4)
Requirement already satisfied: ipython in /opt/anaconda3/lib/python3.12/site-packages (from datascience) (8.25.0)
Requirement already satisfied: plotly in /opt/anaconda3/lib/python3.12/site-packages (from datascience) (5.22.0)
Requirement already satisfied: branca in /opt/anaconda3/lib/python3.12/site-packages (from datascience) (0.7.2)
Requirement already satisfied: jinja2>=2.9 in /opt/anaconda3/lib/python3.12/site-packages (from folium>=0.9.1->datascience) (3.1.4)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.12/site-packages (from folium>=0.9.1->datascience) (2.32.2)
Requirement already satisfied: xyzservices in /opt/anaconda3/lib/python3.12/site-packages (from folium>=0.9.1->datascience) (2022.9.0)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.0.0->datascience) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.0.0->datascience) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.0.0->datascience) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.0.0->datascience) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.0.0->datascience) (23.2)
Requirement already satisfied: pillow>=8 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.0.0->datascience) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.0.0->datascience) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib>=3.0.0->datascience) (2.9.0.post0)
Requirement already satisfied: decorator in /opt/anaconda3/lib/python3.12/site-packages (from ipython->datascience) (5.1.1)
Requirement already satisfied: jedi>=0.16 in /opt/anaconda3/lib/python3.12/site-packages (from ipython->datascience) (0.18.1)
Requirement already satisfied: matplotlib-inline in /opt/anaconda3/lib/python3.12/site-packages (from ipython->datascience) (0.1.6)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in /opt/anaconda3/lib/python3.12/site-packages (from ipython->datascience) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from ipython->datascience) (2.15.1)
Requirement already satisfied: stack-data in /opt/anaconda3/lib/python3.12/site-packages (from ipython->datascience) (0.2.0)
Requirement already satisfied: traitlets>=5.13.0 in /opt/anaconda3/lib/python3.12/site-packages (from ipython->datascience) (5.14.3)
Requirement already satisfied: pexpect>4.3 in /opt/anaconda3/lib/python3.12/site-packages (from ipython->datascience) (4.8.0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas->datascience) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas->datascience) (2023.3)
Requirement already satisfied: tenacity>=6.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from plotly->datascience) (8.2.2)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /opt/anaconda3/lib/python3.12/site-packages (from jedi>=0.16->ipython->datascience) (0.8.3)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jinja2>=2.9->folium>=0.9.1->datascience) (2.1.3)
Requirement already satisfied: ptyprocess>=0.5 in /opt/anaconda3/lib/python3.12/site-packages (from pexpect>4.3->ipython->datascience) (0.7.0)
Requirement already satisfied: wcwidth in /opt/anaconda3/lib/python3.12/site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython->datascience) (0.2.5)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil>=2.7->matplotlib>=3.0.0->datascience) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests->folium>=0.9.1->datascience) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests->folium>=0.9.1->datascience) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests->folium>=0.9.1->datascience) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests->folium>=0.9.1->datascience) (2024.6.2)
Requirement already satisfied: executing in /opt/anaconda3/lib/python3.12/site-packages (from stack-data->ipython->datascience) (0.8.3)
Requirement already satisfied: asttokens in /opt/anaconda3/lib/python3.12/site-packages (from stack-data->ipython->datascience) (2.0.5)
Requirement already satisfied: pure-eval in /opt/anaconda3/lib/python3.12/site-packages (from stack-data->ipython->datascience) (0.2.2)

In [6]:
from datascience import Table

# Read the CSV file as a Table
file_path = 'possibles_same_side.csv'  # Replace with your actual file path
possibles = Table.read_table(file_path)

# Display the table
possibles

Start time     | End time       | High frequency (Hz) | Low frequency (Hz) | GOES | Flare | Notes (corona loop brightening, etc.)
2023-1-1/01:30 | 2023-1-1/04:00 | 1e+07               | 50000              | T    | T     | Loop
2023-1-3/06:25 | 2023-1-3/09:00 | 2e+07               | 70000              | T    | T     | Loop
2023-1-4/03:14 | 2023-1-4/03:20 | 1e+07               | 600000             | F    | nan   | nan
2023-1-4/05:53 | 2023-1-4/06:15 | 2e+07               | 300000             | T    | T     | Loop
2023-1-4/09:19 | 2023-1-4/09:24 | 2e+07               | 600000             | F    | nan   | nan
2023-1-4/12:34 | 2023-1-4/12:45 | 1e+07               | 1e+06              | F    | nan   | nan
2023-1-4/14:31 | 2023-1-4/14:34 | 2e+07               | 500000             | F    | nan   | nan
2023-1-5/17:58 | 2023-1-5/18:50 | 2e+07               | 600000             | T    | F     | nan
2023-1-6/05:43 | 2023-1-6/05:55 | 1e+07               | 400000             | F    | nan   | nan
2023-1-6/07:16 | 2023-1-6/07:21 | 1e+07               | 400000             | F    | nan   | nan
... (222 rows omitted)

In [16]:
high_freq = possibles.column(2)
high_freq

array([ 10000000.,  20000000.,  10000000.,  20000000.,  20000000.,
        10000000.,  20000000.,  20000000.,  10000000.,  10000000.,
        10000000.,  20000000.,  20000000.,  10000000.,  10000000.,
        20000000.,  20000000.,  20000000.,  30000000.,  20000000.,
         7000000.,   4000000.,   1000000.,   6000000.,  20000000.,
         5000000.,   3000000.,  20000000.,  20000000.,  20000000.,
        10000000.,  20000000.,  20000000.,  20000000.,  20000000.,
        20000000.,  20000000.,  10000000.,  10000000.,  10000000.,
         6000000.,  20000000.,  10000000.,   8000000.,  20000000.,
         6000000.,   6000000.,   6000000.,  20000000.,  10000000.,
         9000000.,  20000000.,   9000000.,   9000000.,  10000000.,
        10000000.,  10000000.,  10000000.,  20000000.,  20000000.,
        20000000.,  20000000.,  20000000.,  20000000.,  20000000.,
         8000000.,  10000000.,  10000000.,  20000000.,  13000000.,
        20000000.,  20000000.,  20000000.,  20000000.,  20000000.,
        20000000.,  20000000.,  20000000.,  20000000.,   8000000.,
        20000000.,   7000000.,  20000000.,  20000000.,  20000000.,
        20000000.,  20000000.,  10000000.,   6000000.,   7000000.,
         6000000.,   6000000.,  20000000.,  20000000.,  20000000.,
        14000000.,  20000000.,  20000000.,   7000000.,   6000000.,
         7000000.,   7000000.,  10000000.,  12000000.,  20000000.,
        20000000.,  20000000.,   4000000.,   5000000.,  20000000.,
        20000000.,   7000000.,   7000000.,  11000000.,  20000000.,
         1000000.,   3000000.,   2000000.,  20000000.,   3000000.,
         5000000.,   6000000.,  20000000.,  20000000.,   7000000.,
        20000000.,  14000000.,  20000000.,  10000000.,  14000000.,
        20000000.,  11000000.,   5000000.,  15000000.,  12000000.,
        20000000.,  20000000.,  20000000.,  20000000.,  20000000.,
         4000000.,   6000000.,  20000000.,  10000000.,  20000000.,
        12000000.,  20000000.,  20000000.,  20000000.,  20000000.,
        20000000.,  20000000.,  11000000.,  20000000.,  20000000.,
        20000000.,   9000000.,  20000000.,  11000000.,  20000000.,
        20000000.,   7000000.,  10000000.,  20000000.,  20000000.,
        20000000.,  13000000.,  20000000.,  20000000.,  20000000.,
        10000000.,  20000000.,   9000000.,  13000000.,  20000000.,
        20000000.,   5000000.,  20000000.,  20000000.,  20000000.,
        20000000.,  20000000.,  15000000.,  12000000.,  20000000.,
        20000000.,  20000000.,  20000000.,  20000000.,  17000000.,
        20000000.,  10000000.,  10000000.,  17000000.,  20000000.,
        20000000.,  20000000.,  14000000.,  20000000.,  20000000.,
        20000000.,  20000000.,  12000000.,  16000000.,  12000000.,
        15000000.,  20000000.,  20000000.,  20000000.,  20000000.,
        20000000.,  20000000.,  20000000.,  20000000.,  20000000.,
        20000000.,  20000000.,  20000000.,  20000000.,  20000000.,
        20000000.,  13000000.,  20000000.,  20000000.,  20000000.,
        13000000.,  20000000.,  20000000.,  20000000.,  20000000.,
        20000000.,  20000000.])

In [18]:
low_freq = possibles.column(3)
freq_change = high_freq - low_freq

In [20]:
possibles.with_column("Change in Frequency", freq_change)

Start time     | End time       | High frequency (Hz) | Low frequency (Hz) | GOES | Flare | Notes (corona loop brightening, etc.) | Change in Frequency
2023-1-1/01:30 | 2023-1-1/04:00 | 1e+07               | 50000              | T    | T     | Loop                                  | 9.95e+06
2023-1-3/06:25 | 2023-1-3/09:00 | 2e+07               | 70000              | T    | T     | Loop                                  | 1.993e+07
2023-1-4/03:14 | 2023-1-4/03:20 | 1e+07               | 600000             | F    | nan   | nan                                   | 9.4e+06
2023-1-4/05:53 | 2023-1-4/06:15 | 2e+07               | 300000             | T    | T     | Loop                                  | 1.97e+07
2023-1-4/09:19 | 2023-1-4/09:24 | 2e+07               | 600000             | F    | nan   | nan                                   | 1.94e+07
2023-1-4/12:34 | 2023-1-4/12:45 | 1e+07               | 1e+06              | F    | nan   | nan                                   | 9e+06
2023-1-4/14:31 | 2023-1-4/14:34 | 2e+07               | 500000             | F    | nan   | nan                                   | 1.95e+07
2023-1-5/17:58 | 2023-1-5/18:50 | 2e+07               | 600000             | T    | F     | nan                                   | 1.94e+07
2023-1-6/05:43 | 2023-1-6/05:55 | 1e+07               | 400000             | F    | nan   | nan                                   | 9.6e+06
2023-1-6/07:16 | 2023-1-6/07:21 | 1e+07               | 400000             | F    | nan   | nan                                   | 9.6e+06
... (222 rows omitted)

In [22]:
from datetime import datetime

date_time_str = '2023-1-1/01:30'
date_time_obj = datetime.strptime(date_time_str, '%Y-%m-%d/%H:%M')

print(date_time_obj)

2023-01-01 01:30:00

In [24]:
def convert_date(date_str):
    date_str = date_str.strip().strip("'")
    return datetime.strptime(date_str, '%Y-%m-%d/%H:%M')

In [26]:
start_time = possibles.apply(convert_date, "Start time")
start_time

array([datetime.datetime(2023, 1, 1, 1, 30),
       datetime.datetime(2023, 1, 3, 6, 25),
       datetime.datetime(2023, 1, 4, 3, 14),
       datetime.datetime(2023, 1, 4, 5, 53),
       datetime.datetime(2023, 1, 4, 9, 19),
       datetime.datetime(2023, 1, 4, 12, 34),
       datetime.datetime(2023, 1, 4, 14, 31),
       datetime.datetime(2023, 1, 5, 17, 58),
       datetime.datetime(2023, 1, 6, 5, 43),
       datetime.datetime(2023, 1, 6, 7, 16),
       datetime.datetime(2023, 1, 6, 7, 36),
       datetime.datetime(2023, 1, 6, 7, 53),
       datetime.datetime(2023, 1, 6, 8, 29),
       datetime.datetime(2023, 1, 6, 9, 36),
       datetime.datetime(2023, 1, 6, 10, 20),
       datetime.datetime(2023, 1, 6, 12, 7),
       datetime.datetime(2023, 1, 6, 21, 48),
       datetime.datetime(2023, 1, 8, 18, 14),
       datetime.datetime(2023, 1, 9, 8, 50),
       datetime.datetime(2023, 1, 9, 14, 43),
       datetime.datetime(2023, 1, 9, 17, 42),
       datetime.datetime(2023, 1, 9, 18, 48),
       datetime.datetime(2023, 1, 9, 20, 52),
       datetime.datetime(2023, 1, 9, 22, 29),
       datetime.datetime(2023, 1, 10, 0, 10),
       datetime.datetime(2023, 1, 10, 3, 38),
       datetime.datetime(2023, 1, 10, 9, 10),
       datetime.datetime(2023, 1, 10, 11, 21),
       datetime.datetime(2023, 1, 10, 12, 42),
       datetime.datetime(2023, 1, 10, 15, 40),
       datetime.datetime(2023, 1, 10, 17, 36),
       datetime.datetime(2023, 1, 10, 17, 58),
       datetime.datetime(2023, 1, 11, 2, 47),
       datetime.datetime(2023, 1, 11, 5, 43),
       datetime.datetime(2023, 1, 11, 5, 52),
       datetime.datetime(2023, 1, 11, 5, 55),
       datetime.datetime(2023, 1, 11, 13, 15),
       datetime.datetime(2023, 1, 11, 17, 18),
       datetime.datetime(2023, 1, 13, 3, 3),
       datetime.datetime(2023, 1, 17, 15, 50),
       datetime.datetime(2023, 1, 19, 1, 28),
       datetime.datetime(2023, 1, 19, 2, 24),
       datetime.datetime(2023, 1, 21, 6, 54),
       datetime.datetime(2023, 1, 21, 7, 18),
       datetime.datetime(2023, 1, 22, 3, 44),
       datetime.datetime(2023, 1, 23, 1, 36),
       datetime.datetime(2023, 1, 23, 3, 15),
       datetime.datetime(2023, 1, 23, 14, 46),
       datetime.datetime(2023, 1, 26, 1, 35),
       datetime.datetime(2023, 1, 27, 1, 40),
       datetime.datetime(2023, 2, 1, 6, 15),
       datetime.datetime(2023, 2, 1, 13, 15),
       datetime.datetime(2023, 2, 2, 6, 0),
       datetime.datetime(2023, 2, 2, 6, 30),
       datetime.datetime(2023, 2, 2, 7, 0),
       datetime.datetime(2023, 2, 3, 7, 12),
       datetime.datetime(2023, 2, 3, 7, 24),
       datetime.datetime(2023, 2, 3, 7, 28),
       datetime.datetime(2023, 2, 3, 23, 45),
       datetime.datetime(2023, 2, 4, 0, 15),
       datetime.datetime(2023, 2, 4, 6, 13),
       datetime.datetime(2023, 2, 4, 6, 23),
       datetime.datetime(2023, 2, 4, 6, 31),
       datetime.datetime(2023, 2, 4, 6, 42),
       datetime.datetime(2023, 2, 4, 7, 17),
       datetime.datetime(2023, 2, 5, 2, 50),
       datetime.datetime(2023, 2, 5, 3, 5),
       datetime.datetime(2023, 2, 5, 3, 22),
       datetime.datetime(2023, 2, 5, 3, 39),
       datetime.datetime(2023, 3, 11, 3, 14),
       datetime.datetime(2023, 3, 11, 14, 19),
       datetime.datetime(2023, 3, 13, 3, 12),
       datetime.datetime(2023, 3, 15, 7, 21),
       datetime.datetime(2023, 3, 15, 14, 15),
       datetime.datetime(2023, 3, 15, 16, 56),
       datetime.datetime(2023, 3, 15, 19, 54),
       datetime.datetime(2023, 3, 17, 6, 39),
       datetime.datetime(2023, 3, 18, 0, 26),
       datetime.datetime(2023, 3, 18, 7, 5),
       datetime.datetime(2023, 3, 20, 1, 5),
       datetime.datetime(2023, 3, 20, 13, 51),
       datetime.datetime(2023, 3, 21, 8, 9),
       datetime.datetime(2023, 3, 21, 10, 16),
       datetime.datetime(2023, 3, 21, 11, 31),
       datetime.datetime(2023, 3, 21, 14, 14),
       datetime.datetime(2023, 3, 21, 22, 38),
       datetime.datetime(2023, 3, 22, 5, 18),
       datetime.datetime(2023, 3, 23, 1, 59),
       datetime.datetime(2023, 3, 23, 17, 19),
       datetime.datetime(2023, 3, 23, 19, 18),
       datetime.datetime(2023, 3, 24, 10, 52),
       datetime.datetime(2023, 3, 24, 14, 32),
       datetime.datetime(2023, 3, 27, 21, 3),
       datetime.datetime(2023, 3, 27, 22, 24),
       datetime.datetime(2023, 3, 28, 18, 53),
       datetime.datetime(2023, 3, 30, 4, 5),
       datetime.datetime(2023, 3, 31, 4, 27),
       datetime.datetime(2023, 4, 1, 2, 55),
       datetime.datetime(2023, 4, 1, 3, 11),
       datetime.datetime(2023, 4, 1, 11, 24),
       datetime.datetime(2023, 4, 2, 20, 16),
       datetime.datetime(2023, 4, 2, 20, 41),
       datetime.datetime(2023, 4, 3, 18, 19),
       datetime.datetime(2023, 4, 3, 19, 21),
       datetime.datetime(2023, 4, 3, 20, 26),
       datetime.datetime(2023, 4, 4, 4, 5),
       datetime.datetime(2023, 4, 4, 5, 43),
       datetime.datetime(2023, 4, 4, 6, 47),
       datetime.datetime(2023, 4, 4, 9, 28),
       datetime.datetime(2023, 4, 4, 10, 59),
       datetime.datetime(2023, 4, 4, 11, 35),
       datetime.datetime(2023, 4, 7, 6, 40),
       datetime.datetime(2023, 4, 7, 11, 20),
       datetime.datetime(2023, 4, 7, 21, 36),
       datetime.datetime(2023, 4, 7, 21, 59),
       datetime.datetime(2023, 4, 8, 9, 36),
       datetime.datetime(2023, 4, 9, 1, 23),
       datetime.datetime(2023, 4, 10, 14, 42),
       datetime.datetime(2023, 4, 11, 0, 42),
       datetime.datetime(2023, 4, 11, 11, 54),
       datetime.datetime(2023, 4, 12, 17, 8),
       datetime.datetime(2023, 4, 15, 13, 3),
       datetime.datetime(2023, 4, 16, 11, 10),
       datetime.datetime(2023, 4, 18, 15, 21),
       datetime.datetime(2023, 4, 18, 18, 7),
       datetime.datetime(2023, 4, 19, 20, 20),
       datetime.datetime(2023, 4, 19, 23, 45),
       datetime.datetime(2023, 4, 20, 6, 55),
       datetime.datetime(2023, 4, 20, 12, 17),
       datetime.datetime(2023, 4, 20, 14, 15),
       datetime.datetime(2023, 4, 21, 3, 28),
       datetime.datetime(2023, 4, 21, 17, 57),
       datetime.datetime(2023, 4, 22, 0, 52),
       datetime.datetime(2023, 4, 22, 1, 38),
       datetime.datetime(2023, 4, 22, 7, 50),
       datetime.datetime(2023, 4, 24, 1, 33),
       datetime.datetime(2023, 4, 28, 23, 29),
       datetime.datetime(2023, 4, 29, 22, 56),
       datetime.datetime(2023, 4, 30, 2, 9),
       datetime.datetime(2023, 4, 30, 13, 3),
       datetime.datetime(2023, 5, 1, 9, 41),
       datetime.datetime(2023, 5, 1, 13, 6),
       datetime.datetime(2023, 5, 1, 13, 44),
       datetime.datetime(2023, 5, 2, 4, 29),
       datetime.datetime(2023, 5, 3, 7, 25),
       datetime.datetime(2023, 5, 4, 21, 34),
       datetime.datetime(2023, 5, 5, 23, 7),
       datetime.datetime(2023, 5, 6, 0, 37),
       datetime.datetime(2023, 5, 8, 10, 57),
       datetime.datetime(2023, 5, 8, 18, 30),
       datetime.datetime(2023, 5, 11, 1, 2),
       datetime.datetime(2023, 5, 11, 8, 50),
       datetime.datetime(2023, 5, 11, 18, 23),
       datetime.datetime(2023, 5, 12, 11, 34),
       datetime.datetime(2023, 5, 16, 13, 35),
       datetime.datetime(2023, 5, 16, 17, 17),
       datetime.datetime(2023, 5, 17, 1, 58),
       datetime.datetime(2023, 5, 17, 15, 8),
       datetime.datetime(2023, 5, 18, 7, 8),
       datetime.datetime(2023, 5, 18, 15, 59),
       datetime.datetime(2023, 5, 18, 20, 51),
       datetime.datetime(2023, 5, 19, 19, 11),
       datetime.datetime(2023, 5, 20, 4, 42),
       datetime.datetime(2023, 5, 22, 2, 20),
       datetime.datetime(2023, 5, 22, 13, 38),
       datetime.datetime(2023, 5, 22, 14, 22),
       datetime.datetime(2023, 5, 23, 10, 42),
       datetime.datetime(2023, 5, 25, 22, 6),
       datetime.datetime(2023, 5, 25, 23, 46),
       datetime.datetime(2023, 5, 27, 0, 39),
       datetime.datetime(2023, 5, 27, 2, 32),
       datetime.datetime(2023, 5, 28, 16, 45),
       datetime.datetime(2023, 5, 28, 17, 37),
       datetime.datetime(2023, 5, 28, 18, 16),
       datetime.datetime(2023, 6, 5, 14, 3),
       datetime.datetime(2023, 6, 5, 18, 11),
       datetime.datetime(2023, 6, 11, 23, 56),
       datetime.datetime(2023, 6, 12, 5, 55),
       datetime.datetime(2023, 6, 12, 6, 55),
       datetime.datetime(2023, 6, 12, 16, 6),
       datetime.datetime(2023, 6, 13, 11, 16),
       datetime.datetime(2023, 6, 13, 15, 8),
       datetime.datetime(2023, 6, 13, 16, 23),
       datetime.datetime(2023, 6, 13, 18, 45),
       datetime.datetime(2023, 6, 14, 11, 51),
       datetime.datetime(2023, 6, 14, 19, 23),
       datetime.datetime(2023, 6, 15, 20, 18),
       datetime.datetime(2023, 6, 16, 4, 48),
       datetime.datetime(2023, 6, 16, 13, 33),
       datetime.datetime(2023, 6, 16, 19, 47),
       datetime.datetime(2023, 6, 18, 9, 43),
       datetime.datetime(2023, 6, 19, 0, 55),
       datetime.datetime(2023, 6, 23, 23, 54),
       datetime.datetime(2023, 6, 24, 9, 10),
       datetime.datetime(2023, 6, 24, 12, 7),
       datetime.datetime(2023, 6, 25, 21, 30),
       datetime.datetime(2023, 6, 26, 11, 39),
       datetime.datetime(2023, 6, 27, 11, 23),
       datetime.datetime(2023, 6, 27, 17, 39),
       datetime.datetime(2023, 6, 27, 20, 40),
       datetime.datetime(2023, 6, 28, 16, 38),
       datetime.datetime(2023, 6, 29, 14, 9),
       datetime.datetime(2023, 7, 1, 4, 34),
       datetime.datetime(2023, 7, 1, 11, 28),
       datetime.datetime(2023, 7, 1, 14, 47),
       datetime.datetime(2023, 7, 2, 12, 29),
       datetime.datetime(2023, 7, 3, 12, 25),
       datetime.datetime(2023, 7, 3, 20, 59),
       datetime.datetime(2023, 7, 4, 3, 53),
       datetime.datetime(2023, 7, 4, 6, 33),
       datetime.datetime(2023, 7, 5, 12, 20),
       datetime.datetime(2023, 7, 6, 19, 29),
       datetime.datetime(2023, 7, 8, 20, 2),
       datetime.datetime(2023, 7, 9, 3, 20),
       datetime.datetime(2023, 7, 9, 8, 30),
       datetime.datetime(2023, 7, 10, 0, 24),
       datetime.datetime(2023, 7, 10, 3, 30),
       datetime.datetime(2023, 7, 10, 17, 29),
       datetime.datetime(2023, 7, 11, 11, 15),
       datetime.datetime(2023, 7, 12, 11, 31),
       datetime.datetime(2023, 7, 14, 9, 21),
       datetime.datetime(2023, 7, 14, 13, 57),
       datetime.datetime(2023, 7, 14, 18, 30),
       datetime.datetime(2023, 7, 15, 0, 6),
       datetime.datetime(2023, 7, 15, 7, 26),
       datetime.datetime(2023, 7, 15, 8, 16),
       datetime.datetime(2023, 7, 15, 10, 6),
       datetime.datetime(2023, 7, 15, 19, 50),
       datetime.datetime(2023, 7, 16, 0, 57),
       datetime.datetime(2023, 7, 16, 4, 52),
       datetime.datetime(2023, 7, 16, 10, 24),
       datetime.datetime(2023, 7, 16, 15, 4)], dtype=object)

In [28]:
end_time = possibles.apply(convert_date, "End time")
difference = end_time - start_time
duration_seconds = [diff.total_seconds() for diff in difference]
possibles = possibles.with_column("Change in Frequency", freq_change).with_column("Duration (seconds)", duration_seconds)
possibles

Start time     | End time       | High frequency (Hz) | Low frequency (Hz) | GOES | Flare | Notes (corona loop brightening, etc.) | Change in Frequency | Duration (seconds)
2023-1-1/01:30 | 2023-1-1/04:00 | 1e+07               | 50000              | T    | T     | Loop                                  | 9.95e+06            | 9000
2023-1-3/06:25 | 2023-1-3/09:00 | 2e+07               | 70000              | T    | T     | Loop                                  | 1.993e+07           | 9300
2023-1-4/03:14 | 2023-1-4/03:20 | 1e+07               | 600000             | F    | nan   | nan                                   | 9.4e+06             | 360
2023-1-4/05:53 | 2023-1-4/06:15 | 2e+07               | 300000             | T    | T     | Loop                                  | 1.97e+07            | 1320
2023-1-4/09:19 | 2023-1-4/09:24 | 2e+07               | 600000             | F    | nan   | nan                                   | 1.94e+07            | 300
2023-1-4/12:34 | 2023-1-4/12:45 | 1e+07               | 1e+06              | F    | nan   | nan                                   | 9e+06               | 660
2023-1-4/14:31 | 2023-1-4/14:34 | 2e+07               | 500000             | F    | nan   | nan                                   | 1.95e+07            | 180
2023-1-5/17:58 | 2023-1-5/18:50 | 2e+07               | 600000             | T    | F     | nan                                   | 1.94e+07            | 3120
2023-1-6/05:43 | 2023-1-6/05:55 | 1e+07               | 400000             | F    | nan   | nan                                   | 9.6e+06             | 720
2023-1-6/07:16 | 2023-1-6/07:21 | 1e+07               | 400000             | F    | nan   | nan                                   | 9.6e+06             | 300
... (222 rows omitted)

In [30]:
drift_rate = possibles.column("Change in Frequency") / possibles.column("Duration (seconds)")
possibles = possibles.with_column("Drift Rate (Hz/s)", drift_rate)
possibles

Start time     | End time       | High frequency (Hz) | Low frequency (Hz) | GOES | Flare | Notes (corona loop brightening, etc.) | Change in Frequency | Duration (seconds) | Drift Rate (Hz/s)
2023-1-1/01:30 | 2023-1-1/04:00 | 1e+07               | 50000              | T    | T     | Loop                                  | 9.95e+06            | 9000               | 1105.56
2023-1-3/06:25 | 2023-1-3/09:00 | 2e+07               | 70000              | T    | T     | Loop                                  | 1.993e+07           | 9300               | 2143.01
2023-1-4/03:14 | 2023-1-4/03:20 | 1e+07               | 600000             | F    | nan   | nan                                   | 9.4e+06             | 360                | 26111.1
2023-1-4/05:53 | 2023-1-4/06:15 | 2e+07               | 300000             | T    | T     | Loop                                  | 1.97e+07            | 1320               | 14924.2
2023-1-4/09:19 | 2023-1-4/09:24 | 2e+07               | 600000             | F    | nan   | nan                                   | 1.94e+07            | 300                | 64666.7
2023-1-4/12:34 | 2023-1-4/12:45 | 1e+07               | 1e+06              | F    | nan   | nan                                   | 9e+06               | 660                | 13636.4
2023-1-4/14:31 | 2023-1-4/14:34 | 2e+07               | 500000             | F    | nan   | nan                                   | 1.95e+07            | 180                | 108333
2023-1-5/17:58 | 2023-1-5/18:50 | 2e+07               | 600000             | T    | F     | nan                                   | 1.94e+07            | 3120               | 6217.95
2023-1-6/05:43 | 2023-1-6/05:55 | 1e+07               | 400000             | F    | nan   | nan                                   | 9.6e+06             | 720                | 13333.3
2023-1-6/07:16 | 2023-1-6/07:21 | 1e+07               | 400000             | F    | nan   | nan                                   | 9.6e+06             | 300                | 32000
... (222 rows omitted)

In [ ]:
drift_rate_mhz = drift_rate/1000000
possibles = possibles.with_column("Drift Rate (MHz/s)", drift_rate_mhz)
possibles

In [ ]:
from datascience import are

bursts = possibles.where("Drift Rate (MHz/s)", are.above_or_equal_to(1))
bursts

In [7]:
def calc_drift_rate(file_path):
    possibles = Table.read_table(file_path)
    
    high_freq = possibles.column(2)
    low_freq = possibles.column(3)
    freq_change = high_freq - low_freq
    
    start_time = possibles.apply(convert_date, "Start time")
    end_time = possibles.apply(convert_date, "End time")
    difference = end_time - start_time
    duration_seconds = [diff.total_seconds() for diff in difference]
    
    possibles = possibles.with_column("Change in Frequency", freq_change).with_column("Duration (seconds)", duration_seconds)

    drift_rate = possibles.column("Change in Frequency") / possibles.column("Duration (seconds)")
    possibles = possibles.with_column("Drift Rate (Hz/s)", drift_rate)

    drift_rate_mhz = drift_rate/1000000
    possibles = possibles.with_column("Drift Rate (MHz/s)", drift_rate_mhz)
    possibles.show()

    return possibles

In [13]:
possibles_dfdt = calc_drift_rate("possibles.csv")

In [19]:
range = (possibles_dfdt.column("High frequency (Hz)") ** 1.84) * 0.01 / 1000000
range

array([  7.58577575e+04,   2.71578379e+05,   7.58577575e+04,
         2.71578379e+05,   7.58577575e+04,   2.71578379e+05,
         7.58577575e+04,   2.71578379e+05,   2.71578379e+05,
         7.58577575e+04,   7.58577575e+04,   7.58577575e+04,
         2.71578379e+05,   2.71578379e+05,   7.58577575e+04,
         7.58577575e+04,   2.71578379e+05,   2.71578379e+05,
         2.71578379e+05,   5.72668254e+05,   2.71578379e+05,
         3.93532309e+04,   1.40536905e+04,   1.09647820e+03,
         2.96345475e+04,   2.71578379e+05,   2.11887242e+04,
         8.27757470e+03,   2.71578379e+05,   2.71578379e+05,
         2.71578379e+05,   7.58577575e+04,   2.71578379e+05,
         2.71578379e+05,   2.71578379e+05,   2.71578379e+05,
         2.71578379e+05,   2.71578379e+05,   7.58577575e+04,
         7.58577575e+04,   7.58577575e+04,   2.96345475e+04,
         2.71578379e+05,   7.58577575e+04,   5.03136212e+04,
         2.71578379e+05,   2.96345475e+04,   2.96345475e+04,
         2.96345475e+04,   2.71578379e+05,   7.58577575e+04,
         6.24893802e+04,   2.71578379e+05,   6.24893802e+04,
         6.24893802e+04,   7.58577575e+04,   7.58577575e+04,
         7.58577575e+04,   7.58577575e+04,   2.71578379e+05,
         2.71578379e+05,   2.71578379e+05,   2.71578379e+05,
         2.71578379e+05,   2.71578379e+05,   2.71578379e+05,
         5.03136212e+04,   7.58577575e+04,   7.58577575e+04,
         2.71578379e+05,   2.96345475e+04,   3.92550190e+03,
         2.71578379e+05,   2.71578379e+05,   7.58577575e+04,
         2.71578379e+05,   7.58577575e+04,   2.71578379e+05,
         2.96345475e+04,   2.11887242e+04,   7.58577575e+04,
         6.24893802e+04,   7.58577575e+04,   7.58577575e+04,
         5.03136212e+04,   7.58577575e+04,   7.58577575e+04,
         2.71578379e+05,   5.03136212e+04,   2.71578379e+05,
         2.71578379e+05,   7.58577575e+04,   2.71578379e+05,
         2.71578379e+05,   7.58577575e+04,   2.11887242e+04,
         2.71578379e+05,   2.71578379e+05,   2.71578379e+05,
         7.58577575e+04,   7.58577575e+04,   7.58577575e+04,
         1.40536905e+04,   2.71578379e+05,   2.71578379e+05,
         2.71578379e+05,   3.93532309e+04,   7.58577575e+04,
         2.96345475e+04,   7.58577575e+04,   3.93532309e+04,
         7.58577575e+04,   3.92550190e+03,   7.58577575e+04,
         2.71578379e+05,   2.71578379e+05,   2.71578379e+05,
         2.71578379e+05,   2.11887242e+04,   3.92550190e+03,
         2.11887242e+04,   2.96345475e+04,   8.27757470e+03,
         2.71578379e+05,   2.71578379e+05,   8.27757470e+03,
         7.58577575e+04,   5.03136212e+04,   2.11887242e+04,
         7.58577575e+04,   3.93532309e+04,   3.93532309e+04,
         7.58577575e+04,   2.96345475e+04,   3.92550190e+03,
         2.11887242e+04,   7.58577575e+04,   7.58577575e+04,
         2.71578379e+05,   3.92550190e+03,   1.40536905e+04,
         2.71578379e+05,   3.93532309e+04,   2.11887242e+04,
         2.96345475e+04,   2.71578379e+05,   7.58577575e+04,
         3.93532309e+04,   2.71578379e+05,   2.11887242e+04,
         8.27757470e+03,   1.40536905e+04,   2.71578379e+05,
         2.71578379e+05,   2.71578379e+05,   3.92550190e+03,
         2.71578379e+05,   5.68827250e+02,   2.71578379e+05,
         2.71578379e+05,   3.93532309e+04,   3.93532309e+04,
         2.71578379e+05,   8.27757470e+03,   8.27757470e+03,
         1.40536905e+04,   8.27757470e+03,   1.09647820e+03,
         2.71578379e+05,   2.71578379e+05,   7.58577575e+04,
         2.71578379e+05,   2.11887242e+04,   1.40536905e+04,
         2.11887242e+04,   2.96345475e+04,   7.58577575e+04])

In [21]:
possibles_dfdt.with_columns("Range", range)

Start time     | End time       | High frequency (Hz) | Low frequency (Hz) | Change in Frequency | Duration (seconds) | Drift Rate (Hz/s) | Drift Rate (MHz/s) | Range
2023-1-1/01:30 | 2023-1-1/04:00 | 1e+07               | 50000              | 9.95e+06            | 9000               | 1105.56           | 0.00110556         | 75857.8
2023-1-3/06:25 | 2023-1-3/09:00 | 2e+07               | 70000              | 1.993e+07           | 9300               | 2143.01           | 0.00214301         | 271578
2023-1-4/03:14 | 2023-1-4/03:20 | 1e+07               | 600000             | 9.4e+06             | 360                | 26111.1           | 0.0261111          | 75857.8
2023-1-4/05:53 | 2023-1-4/06:15 | 2e+07               | 300000             | 1.97e+07            | 1320               | 14924.2           | 0.0149242          | 271578
2023-1-4/03:14 | 2023-1-4/03:29 | 1e+07               | 600000             | 9.4e+06             | 900                | 10444.4           | 0.0104444          | 75857.8
2023-1-4/09:19 | 2023-1-4/09:24 | 2e+07               | 600000             | 1.94e+07            | 300                | 64666.7           | 0.0646667          | 271578
2023-1-4/12:34 | 2023-1-4/12:45 | 1e+07               | 1e+06              | 9e+06               | 660                | 13636.4           | 0.0136364          | 75857.8
2023-1-4/14:31 | 2023-1-4/14:34 | 2e+07               | 500000             | 1.95e+07            | 180                | 108333            | 0.108333           | 271578
2023-1-5/17:58 | 2023-1-5/18:50 | 2e+07               | 600000             | 1.94e+07            | 3120               | 6217.95           | 0.00621795         | 271578
2023-1-6/05:43 | 2023-1-6/05:55 | 1e+07               | 400000             | 9.6e+06             | 720                | 13333.3           | 0.0133333          | 75857.8
... (167 rows omitted)

In [ ]:
bursts = np.count_nonzero(possibles_dfdt.column("Drift Rate (MHz/s)") > range)
bursts

In [52]:
from datascience import Table
from datetime import datetime

possibles_dfdt = calc_drift_rate("possibles.csv")

In [ ]:
possibles_dfdt.hist("Drift Rate (MHz/s)")

In [ ]:
pip list

In [15]:
from pytplot import get_data
from matplotlib import pyplot as plt
%matplotlib tk
from matplotlib.colors import LogNorm

In [ ]:
# plt.hist(possibles_dfdt.column("Duration (seconds)"))
# plt.show()

In [47]:
possibles_dfdt.sort("Drift Rate (MHz/s)", descending = True)

Start time      | End time        | High frequency (Hz) | Low frequency (Hz) | Change in Frequency | Duration (seconds) | Drift Rate (Hz/s) | Drift Rate (MHz/s)
2023-1-4/14:31  | 2023-1-4/14:34  | 2e+07               | 500000             | 1.95e+07            | 180                | 108333            | 0.108333
2023-2-16/23:01 | 2023-2-16/23:04 | 2e+07               | 1e+06              | 1.9e+07             | 180                | 105556            | 0.105556
2023-2-19/19:21 | 2023-2-19/19:24 | 2e+07               | 5e+06              | 1.5e+07             | 180                | 83333.3           | 0.0833333
2023-2-16/12:37 | 2023-2-16/12:41 | 2e+07               | 1e+06              | 1.9e+07             | 240                | 79166.7           | 0.0791667
2023-1-4/09:19  | 2023-1-4/09:24  | 2e+07               | 600000             | 1.94e+07            | 300                | 64666.7           | 0.0646667
2023-2-13/20:36 | 2023-2-13/20:41 | 2e+07               | 600000             | 1.94e+07            | 300                | 64666.7           | 0.0646667
2023-2-20/23:45 | 2023-2-20/23:52 | 2e+07               | 600000             | 1.94e+07            | 420                | 46190.5           | 0.0461905
2023-2-13/19:36 | 2023-2-13/19:45 | 2e+07               | 400000             | 1.96e+07            | 540                | 36296.3           | 0.0362963
2023-2-10/02:56 | 2023-2-10/03:05 | 2e+07               | 500000             | 1.95e+07            | 540                | 36111.1           | 0.0361111
2023-2-15/20:51 | 2023-2-15/21:00 | 2e+07               | 600000             | 1.94e+07            | 540                | 35925.9           | 0.0359259
... (167 rows omitted)

In [54]:
possibles_dfdt.scatter("Low frequency (Hz)", "High frequency (Hz)")

In [17]:
import matplotlib.pyplot as plt

low_freq = possibles_dfdt.column("Low frequency (Hz)") / 1000000
high_freq = possibles_dfdt.column("High frequency (Hz)") / 1000000

plt.scatter(low_freq, high_freq)

plt.xscale('log')
plt.yscale('log')

plt.xlabel('Low frequency (MHz)')
plt.ylabel('High frequency (MHz)')

plt.show()

In [37]:
possibles_dfdt.scatter("Duration (seconds)", "High frequency (Hz)")

In [43]:
duration = possibles_dfdt.column("Duration (seconds)")
high_freq = possibles_dfdt.column("High frequency (Hz)") / 1000000

plt.scatter(high_freq, duration)

plt.xscale('log')
plt.yscale('log')

plt.xlabel('Duration (s)')
plt.ylabel('High frequency (MHz)')

plt.show()

In [45]:
duration = possibles_dfdt.column("Duration (seconds)")
freq_diff = possibles_dfdt.column("Change in Frequency") / 1000000

plt.scatter(duration, freq_diff)

plt.xscale('log')
plt.yscale('log')

plt.xlabel('Duration (s)')
plt.ylabel('Freq Diff (MHz)')

plt.show()

In [32]:
possibles.hist("Drift Rate (Hz/s)")