In [1]:
import numpy as np
import pandas as pd
from IPython.display import FileLink
from pytplot import get_data
from matplotlib import pyplot as plt
%matplotlib tk
from matplotlib.colors import LogNorm
from sklearn.linear_model import LinearRegression
from adjustText import adjust_text

file_path = 'stereo_maven_psp_both.csv'
bursts = pd.read_csv(file_path)
print(bursts.head())

         Start time          End time  High frequency (Hz)  \
0  2021-09-21T09:43  2021-09-21T10:50             15000000
1  2021-10-28T15:30  2021-10-28T19:15             15000000
2  2022-02-15T21:55  2022-02-16T00:25             10000000
3  2022-05-08T02:00  2022-05-08T02:50              5000000
4  2022-05-17T20:37  2022-05-17T21:54              2300000

   Low frequency (Hz) Notes      Start time.1        End time.1  \
0               40000   NaN  2021-09-21T09:40  2021-09-21T10:27
1               20000   NaN  2021-10-28T15:25  2021-10-28T19:15
2               40000   NaN  2022-02-15T21:50  2022-02-16T03:20
3              100000   NaN  2022-05-08T20:55  2022-05-08T21:30
4               70000   NaN  2022-05-17T20:30  2022-05-17T21:55

   High frequency (Hz).1  Low frequency (Hz).1       Notes.1
0               20000000                 80000  Very obvious
1               20000000                 40000  Very obvious
2               20000000                 30000           NaN
3               20000000                130000           NaN
4               20000000                 60000           NaN

In [2]:
stereo = bursts.iloc[:, 0:5]
psp = bursts.iloc[:, 5:10]
psp.columns = [col.replace('.1', '') for col in psp.columns]

In [3]:
import radio_burst_analysis
from radio_burst_analysis import *
from importlib import reload
reload(radio_burst_analysis)

In [4]:
stereo = calc_drift_rate(stereo)
psp = calc_drift_rate(psp)
stereo.head()

,Start time,End time,High frequency (Hz),Low frequency (Hz),Notes,Frequency Change,Duration (seconds),Drift Rate (Hz/s)
0,2021-09-21 09:43:00,2021-09-21 10:50:00,15000000,40000,NaN,14960000,4020.0,3721.393035
1,2021-10-28 15:30:00,2021-10-28 19:15:00,15000000,20000,NaN,14980000,13500.0,1109.629630
2,2022-02-15 21:55:00,2022-02-16 00:25:00,10000000,40000,NaN,9960000,9000.0,1106.666667
3,2022-05-08 02:00:00,2022-05-08 02:50:00,5000000,100000,NaN,4900000,3000.0,1633.333333
4,2022-05-17 20:37:00,2022-05-17 21:54:00,2300000,70000,NaN,2230000,4620.0,482.683983

In [5]:
make_csv(stereo, 'stereo')
make_csv(psp, 'psp')

In [6]:
file_path = 'maven_descending_full_clean.csv'

maven = pd.read_csv(file_path)

print(maven.head())

   Start Time (UTC)    End Time (UTC)   Start Energy (keV)   End Energy (keV)  \
0  2015-04-21T11:25  2015-04-21T12:50                   80                 20
1  2015-04-21T12:55  2015-04-21T14:35                    5                  2
2  2016-01-06T14:50  2016-01-06T16:24                  150                 20
3  2018-05-05T14:15  2018-05-05T14:52                   40                 20
4  2021-09-21T10:50  2021-09-21T12:05                   80                 20

   Instrument                                              Notes
0         SEP   followed by SWEA descending tone; no EUV cove...
1        SWEA                                                NaN
2         SEP  SEP rapid rise in intensity at 15:10 and decli...
3         SEP                               no flare seen in EUV
4         SEP                                                NaN

In [7]:
maven = calc_drift_rate_energy(maven)
make_csv(maven, 'maven')

In [8]:
merged = merge_common_date(stereo, psp, maven, "STEREO", "PSP", "MAVEN")

23-Jul-25 13:13:01: /Users/liu/Library/Mobile Documents/com~apple~CloudDocs/Berkeley/Research/summer_lab/compare_maven/radio_burst_analysis.py:49: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset1_common['Source'] = label1

23-Jul-25 13:13:01: /Users/liu/Library/Mobile Documents/com~apple~CloudDocs/Berkeley/Research/summer_lab/compare_maven/radio_burst_analysis.py:50: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset2_common['Source'] = label2

23-Jul-25 13:13:01: /Users/liu/Library/Mobile Documents/com~apple~CloudDocs/Berkeley/Research/summer_lab/compare_maven/radio_burst_analysis.py:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dataset3_common['Source'] = label3

In [9]:
merged = merged.drop(range(15, 21), axis=0)
merged = merged.drop(range(25, 31), axis=0)
merged = merged.drop(range(39, 47), axis=0)
merged = merged.drop(range(48, 50), axis=0)
merged

,Start time_stereo,End time_stereo,High frequency (Hz)_stereo,Low frequency (Hz)_stereo,Notes_stereo,Frequency Change_stereo,Duration (seconds)_stereo,Drift Rate (Hz/s)_stereo,Date,Source_stereo,...,Source_psp,Start Time (UTC),End Time (UTC),Start Energy (keV),End Energy (keV),Instrument,Notes,Duration (seconds),Energy Change (keV),Source
0,2021-09-21 09:43:00,2021-09-21 10:50:00,15000000,40000,NaN,14960000,4020.0,3721.393035,2021-09-21,STEREO,...,PSP,2021-09-21 10:50:00,2021-09-21 12:05:00,80,20,SEP,NaN,4500.0,60,MAVEN
1,2021-10-28 15:30:00,2021-10-28 19:15:00,15000000,20000,NaN,14980000,13500.0,1109.629630,2021-10-28,STEREO,...,PSP,2021-10-28 16:55:00,2021-10-28 18:37:00,100,20,SEP,leads into a hefty SEP electron event so mayb...,6120.0,80,MAVEN
2,2022-02-15 21:55:00,2022-02-16 00:25:00,10000000,40000,NaN,9960000,9000.0,1106.666667,2022-02-15,STEREO,...,PSP,2022-02-15 22:55:00,2022-02-16 01:00:00,100,20,SEP,leads into a SEP event so maybe flare but poo...,7500.0,80,MAVEN
3,2022-05-08 02:00:00,2022-05-08 02:50:00,5000000,100000,NaN,4900000,3000.0,1633.333333,2022-05-08,STEREO,...,PSP,2022-05-08 05:25:00,2022-05-08 06:30:00,80,20,SEP,NaN,3900.0,60,MAVEN
4,2022-05-17 20:37:00,2022-05-17 21:54:00,2300000,70000,NaN,2230000,4620.0,482.683983,2022-05-17,STEREO,...,PSP,2022-05-17 22:15:00,2022-05-18 00:30:00,60,20,SEP,NaN,8100.0,40,MAVEN
5,2022-06-29 17:37:00,2022-06-29 18:00:00,1000000,70000,NaN,930000,1380.0,673.913043,2022-06-29,STEREO,...,PSP,2022-06-29 20:45:00,2022-06-29 21:30:00,80,20,SEP,only seen in 2F,2700.0,60,MAVEN
6,2022-06-30 05:05:00,2022-06-30 05:37:00,6700000,70000,NaN,6630000,1920.0,3453.125000,2022-06-30,STEREO,...,PSP,2022-06-30 05:30:00,2022-06-30 08:30:00,100,20,SEP,on top of minor SEP event,10800.0,80,MAVEN
7,2022-07-01 11:37:00,2022-07-01 12:08:00,15000000,100000,NaN,14900000,1860.0,8010.752688,2022-07-01,STEREO,...,PSP,2022-07-01 16:25:00,2022-07-01 17:00:00,80,20,SEP,low intensity and on top of minor SEP event,2100.0,60,MAVEN
8,2022-07-22 13:05:00,2022-07-22 13:32:00,3500000,40000,NaN,3460000,1620.0,2135.802469,2022-07-22,STEREO,...,PSP,2022-07-22 17:55:00,2022-07-22 21:05:00,80,20,SEP,very clear signature,11400.0,60,MAVEN
9,2022-11-17 09:16:00,2022-11-17 11:24:00,10000000,50000,NaN,9950000,7680.0,1295.572917,2022-11-17,STEREO,...,PSP,2022-11-17 10:20:00,2022-11-17 12:50:00,40,20,SEP,NaN,9000.0,20,MAVEN
10,2022-12-27 17:30:00,2022-12-27 21:30:00,7000000,20000,NaN,6980000,14400.0,484.722222,2022-12-27,STEREO,...,PSP,2022-12-27 18:13:00,2022-12-27 19:05:00,80,20,SEP,intense signature; end of DSW event,3120.0,60,MAVEN
11,2023-03-02 17:40:00,2023-03-02 19:55:00,10000000,20000,NaN,9980000,8100.0,1232.098765,2023-03-02,STEREO,...,PSP,2023-03-02 18:20:00,2023-03-02 19:30:00,50,20,SEP,"anisotropic (primarily in 1R and 2F, much less...",4200.0,30,MAVEN
12,2023-07-11 11:20:00,2023-07-11 12:26:00,15000000,70000,NaN,14930000,3960.0,3770.202020,2023-07-11,STEREO,...,PSP,2023-07-11 12:05:00,2023-07-11 13:20:00,70,20,SEP,"mostly in 1R, 2R, and 2F (little in 1F)",4500.0,50,MAVEN
13,2023-07-15 07:30:00,2023-07-15 13:35:00,15000000,8000,Very obvious,14992000,21900.0,684.566210,2023-07-15,STEREO,...,PSP,2023-07-15 08:45:00,2023-07-15 10:00:00,80,20,SEP,mostly in 2F; trailing an M1.8 flare seen in EUV,4500.0,60,MAVEN
14,2023-09-19 20:10:00,2023-09-19 21:30:00,15000000,80000,NaN,14920000,4800.0,3108.333333,2023-09-19,STEREO,...,PSP,2023-09-19 20:30:00,2023-09-19 22:00:00,200,20,SEP,look flare related since abnormally high energy,5400.0,180,MAVEN
21,2023-09-19 22:30:00,2023-09-19 23:40:00,15000000,70000,NaN,14930000,4200.0,3554.761905,2023-09-19,STEREO,...,PSP,2023-09-19 23:00:00,2023-09-20 02:00:00,100,20,SEP,NaN,10800.0,80,MAVEN
22,2024-01-10 19:00:00,2024-01-11 00:30:00,15000000,24000,Trigger vertical line preceding,14976000,19800.0,756.363636,2024-01-10,STEREO,...,PSP,2024-01-10 21:30:00,2024-01-10 23:30:00,50,20,SEP,NaN,7200.0,30,MAVEN
23,2024-04-03 17:35:00,2024-04-03 19:00:00,5000000,60000,NaN,4940000,5100.0,968.627451,2024-04-03,STEREO,...,PSP,2024-04-03 18:20:00,2024-04-03 19:45:00,50,20,SEP,starts while s/c in periapse so hard to ident...,5100.0,30,MAVEN
24,2024-05-01 18:15:00,2024-05-01 18:38:00,15000000,150000,NaN,14850000,1380.0,10760.869565,2024-05-01,STEREO,...,PSP,2024-05-01 18:35:00,2024-05-01 19:40:00,50,20,SEP,dim,3900.0,30,MAVEN
31,2024-05-01 20:05:00,2024-05-01 20:40:00,15000000,130000,NaN,14870000,2100.0,7080.952381,2024-05-01,STEREO,...,PSP,2024-05-01 22:10:00,2024-05-01 23:04:00,80,23,SEP,primarily in 1R and 2F with little in the othe...,3240.0,57,MAVEN
32,2024-07-10 21:10:00,2024-07-11 00:30:00,1000000,30000,NaN,970000,12000.0,80.833333,2024-07-10,STEREO,...,PSP,2024-07-10 21:50:00,2024-07-10 23:30:00,100,26,SEP,NaN,6000.0,74,MAVEN
33,2024-07-29 01:10:00,2024-07-29 02:46:00,15000000,70000,NaN,14930000,5760.0,2592.013889,2024-07-29,STEREO,...,PSP,2024-07-29 01:20:00,2024-07-29 02:00:00,50,20,SEP,NaN,2400.0,30,MAVEN
34,2024-07-29 01:10:00,2024-07-29 02:46:00,15000000,70000,NaN,14930000,5760.0,2592.013889,2024-07-29,STEREO,...,PSP,2024-07-29 10:20:00,2024-07-29 12:40:00,100,20,SEP,strongest in 2F,8400.0,80,MAVEN
35,2024-08-05 13:45:00,2024-08-05 21:50:00,10000000,26000,Very obvious,9974000,29100.0,342.749141,2024-08-05,STEREO,...,PSP,2024-08-05 14:05:00,2024-08-05 15:15:00,150,20,SEP,mostly isotropic although less strong in 1F in...,4200.0,130,MAVEN
36,2024-08-07 13:45:00,2024-08-07 15:20:00,15000000,50000,Trigger vertical line preceding,14950000,5700.0,2622.807018,2024-08-07,STEREO,...,PSP,2024-08-07 14:45:00,2024-08-07 15:45:00,50,20,SEP,mostly isotropic although less strong in 1F,3600.0,30,MAVEN
37,2024-09-03 07:50:00,2024-09-03 12:00:00,6000000,30000,NaN,5970000,15000.0,398.000000,2024-09-03,STEREO,...,PSP,2024-09-03 08:35:00,2024-09-03 10:10:00,150,20,SEP,~45 min after a M6.3 flare seen in EUV so may ...,5700.0,130,MAVEN
38,2024-09-09 00:45:00,2024-09-09 05:35:00,3000000,40000,NaN,2960000,17400.0,170.114943,2024-09-09,STEREO,...,PSP,2024-09-09 01:45:00,2024-09-09 04:20:00,90,20,SEP,simultaneous to a M1.2 flare seen by EUV,9300.0,70,MAVEN
47,2024-09-09 14:15:00,2024-09-09 16:20:00,600000,50000,NaN,550000,7500.0,73.333333,2024-09-09,STEREO,...,PSP,2024-09-09 14:30:00,2024-09-09 16:30:00,150,20,SEP,NaN,7200.0,130,MAVEN

In [10]:
merged
merged.to_csv("merged.csv", index=False)

In [11]:
plot_energy_change_vs_duration(maven, "MAVEN")

In [12]:
plot_freq_change_vs_energy_change(merged, "STEREO", "PSP")

Hit enter to continue:

In [13]:
# Power law model for stereo
plt.figure(figsize=(10, 6))
plot_power_fit(plt, merged, "stereo", 0)
plt.show()

Power law model for stereo: y = 3.455e+07 * x^-0.383

In [14]:
# Power law model for psp
plt.figure(figsize=(10, 6))
plot_power_fit(plt, merged, "psp", 0)
plt.show()

Power law model for psp: y = 2.188e+07 * x^-0.159

In [42]:
# Power law model for both overlapped
plt.figure(figsize=(10, 6))
plot_power_fit(plt, merged, "stereo", 0)
plot_power_fit(plt, merged, "psp", 1)
plt.show()

Power law model for stereo: y = 3.455e+07 * x^-0.383
Power law model for psp: y = 2.188e+07 * x^-0.159

In [16]:
plt.figure(figsize=(10, 6))
plot_cubic_fit(plt, merged, "stereo", 0)
plt.show()

Cubic model for stereo: y = 9.62e+06 + 1.22e+05*x + -2.65e+03*x² + 1.17e+01*x³

In [17]:
plt.figure(figsize=(10, 6))
plot_cubic_fit(plt, merged, "psp", 0)
plt.show()

Cubic model for psp: y = 8.47e+06 + 3.63e+05*x + -5.58e+03*x² + 2.18e+01*x³

In [61]:
plt.figure(figsize=(10, 6))
plot_cubic_fit(plt, merged, "stereo", 0)
plot_cubic_fit(plt, merged, "psp", 1)
plt.show()

Cubic model for stereo: y = 9.62e+06 + 1.22e+05*x + -2.65e+03*x² + 1.17e+01*x³
Cubic model for psp: y = 8.47e+06 + 3.63e+05*x + -5.58e+03*x² + 2.18e+01*x³